import type { Segment, TranscriptLine } from './types'

export type CuratedSourceStatus = 'ready' | 'curating' | 'queued'

export interface CuratedCollection {
  id: string
  speakerId: string
  speaker: string
  sourceTitle: string
  videoId: string | null
  videoTitle: string
  channelName: string
  thumbnail: string
  duration: number
  description: string
  focus: string[]
  status: CuratedSourceStatus
  segments: Segment[]
}

export interface CuratedSpeaker {
  id: string
  name: string
  description: string
  focus: string[]
  portrait: string
  sources: CuratedCollection[]
}

const segment = (id: string, start: number, end: number, label: string): Segment => ({
  id,
  start,
  end,
  label,
  lines: [],
  createdAt: 0,
})

const transcriptLine = (text: string, start: number, duration: number): TranscriptLine => ({
  text,
  start,
  duration,
})

const segmentWithLines = (
  id: string,
  start: number,
  end: number,
  label: string,
  lines: TranscriptLine[],
): Segment => ({
  id,
  start,
  end,
  label,
  lines,
  createdAt: 0,
})

const navalJre: CuratedCollection = {
  id: 'naval-jre-1309',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Joe Rogan Experience #1309',
  videoId: '3qHkcs3kG44',
  videoTitle: 'Joe Rogan Experience #1309 - Naval Ravikant',
  channelName: 'PowerfulJRE',
  thumbnail: 'https://i.ytimg.com/vi/3qHkcs3kG44/hqdefault.jpg',
  duration: 7917,
  description: 'Relaxed long-form Naval. Strong baseline for formulation, analogy, calm pacing, compression, disagreement, and clean endings.',
  focus: ['Formulation', 'Articulation', 'Cadence', 'Compression', 'Explanation', 'Analogy'],
  status: 'ready',
  segments: [
    segment('JRE1309-001', 46, 78, 'Analogy · vivid answer opening'),
    segment('JRE1309-002', 144, 175, 'Analogy · mountain-climbing reframe'),
    segment('JRE1309-003', 201, 240, 'Formulation · beginner’s mind'),
    segment('JRE1309-004', 241, 255, 'Distinction · knowing vs understanding'),
    segment('JRE1309-005', 304, 327, 'Compression · lecture → book → blog → tweet'),
    segment('JRE1309-006', 401, 426, 'Explanation · curiosity over completion'),
    segment('JRE1309-007', 866, 887, 'Formulation · concise communication'),
    segment('JRE1309-008', 918, 935, 'Formulation · calmness under pressure'),
    segment('JRE1309-009', 1015, 1045, 'Qualification · state, soften, restate'),
    segment('JRE1309-010', 1099, 1126, 'Definition · desire'),
    segment('JRE1309-011', 1301, 1333, 'Analogy · nonlinear work output'),
    segment('JRE1309-012', 1358, 1385, 'Cadence · train, sprint, rest, reassess'),
    segment('JRE1309-013', 1751, 1776, 'Disagreement · unpopular view + context'),
    segment('JRE1309-014', 2360, 2377, 'Strong ending · creativity reframe'),
    segment('JRE1309-015', 4580, 4596, 'Formulation · inherited beliefs'),
    segment('JRE1309-016', 4627, 4651, 'Compression · diseases of abundance'),
    segment('JRE1309-017', 4691, 4705, 'Storytelling · setup → reversal → landing'),
    segment('JRE1309-018', 4887, 4919, 'Explanation · deliberate instructional pacing'),
    segment('JRE1309-019', 5017, 5053, 'Formulation · peace and happiness'),
    segment('JRE1309-020', 5451, 5463, 'Uncertainty · trade-offs, not perfect answers'),
    segment('JRE1309-021', 5692, 5710, 'Explanation · writing tests understanding'),
    segment('JRE1309-022', 5963, 5989, 'Formulation · reasoning through paradox'),
    segment('JRE1309-023', 6451, 6500, 'Distinction · peace of mind vs peace from mind'),
    segment('JRE1309-024', 6530, 6539, 'Humor · compact setup and reversal'),
    segment('JRE1309-025', 6591, 6617, 'Explanation · structured three-part definition'),
    segment('JRE1309-026', 6723, 6747, 'Compression · authenticity → leverage → ownership'),
    segment('JRE1309-027', 7093, 7122, 'Formulation · contrast → insight → rule'),
    segment('JRE1309-028', 7558, 7583, 'Explanation · self-questioning → decision rule'),
    segment('JRE1309-029', 7673, 7708, 'Reframing · rebuild a cliché precisely'),
    segment('JRE1309-030', 7760, 7809, 'Answer opening · direct answer before expansion'),
  ],
}

const navalModernWisdom: CuratedCollection = {
  id: 'naval-modern-wisdom-922',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Modern Wisdom #922 · 44 Harsh Truths About Human Nature',
  videoId: 'KyfUysrNaco',
  videoTitle: '44 Harsh Truths About The Game Of Life - Naval Ravikant',
  channelName: 'Chris Williamson',
  thumbnail: 'https://i.ytimg.com/vi/KyfUysrNaco/hqdefault.jpg',
  duration: 11820,
  description: 'A later, more polished Naval. Excellent for self-correction, compressed definitions, first-principles explanation, qualification, and strong conceptual framing.',
  focus: ['Formulation', 'Self-correction', 'Definition', 'First principles', 'Reframing', 'Strong endings'],
  status: 'ready',
  segments: [
    segment('MW922-001', 7.3, 18.2, 'Self-correction · update an old belief cleanly'),
    segment('MW922-002', 27.3, 39.1, 'Story → principle · freedom through not wanting'),
    segment('MW922-003', 477, 491, 'Compression · choose your desires to focus'),
    segment('MW922-004', 534, 560, 'Qualification · fame, consistency, and performance'),
    segment('MW922-005', 1295, 1322, 'Definition · self-esteem as self-reputation'),
    segment('MW922-006', 1796, 1818, 'Formulation · pride is the enemy of learning'),
    segment('MW922-007', 2409, 2437, 'Instruction · protect life from low-value obligations'),
    segment('MW922-008', 2487, 2527, 'Cadence · inspiration is perishable'),
    segment('MW922-009', 2684, 2706, 'Analogy · play to you, work to others'),
    segment('MW922-010', 2732, 2755, 'Compression · authenticity → productize yourself'),
    segment('MW922-011', 3010, 3041, 'Explanation · create distance from your own thoughts'),
    segment('MW922-012', 3067, 3094, 'Reframing · problems must enter the mind first'),
    segment('MW922-013', 3335, 3378, 'Definition · intelligence has two parts'),
    segment('MW922-014', 4913, 4943, 'Analogy · stress as conflicting desires'),
    segment('MW922-015', 5900, 5940, 'Decision rule · what you accept shapes your life'),
    segment('MW922-016', 7703, 7738, 'Meta-formulation · performance vs genuine thought'),
    segment('MW922-017', 8219, 8253, 'Formulation · deep understanding re-derives itself'),
    segment('MW922-018', 8274, 8321, 'Distinction · understanding beats memorization'),
    segment('MW922-019', 8321, 8351, 'Definition · philosophy as generalized experience'),
    segment('MW922-020', 11383, 11420, 'Analogy · cut the Gordian knot of the past'),
    segment('MW922-021', 11420, 11471, 'Strong ending · attention is the currency of life'),
  ],
}

const navalKnowledgeProject18: CuratedCollection = {
  id: 'naval-knowledge-project-18',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'The Knowledge Project #18 · 2017',
  videoId: 'mGY2To_HW98',
  videoTitle: 'The Angel Philosopher Naval Ravikant on Reading, Making Decisions, Habits, and the Purpose of Life',
  channelName: 'The Knowledge Project',
  thumbnail: 'https://i.ytimg.com/vi/mGY2To_HW98/hqdefault.jpg',
  duration: 7262,
  description: 'Early long-form Naval with unusually rich thinking aloud: reading, habits, happiness, values, science, decision-making, integrity, and meaning. Selected primarily for formulation quality and trainable conceptual structure.',
  focus: ['Formulation', 'Articulation', 'Explanation', 'Reasoning', 'Reframing', 'Thinking aloud'],
  status: 'ready',
  segments: [
    segment('TKP18-001', 842, 884, 'Reframing · treat a book like a blog archive'),
    segment('TKP18-002', 940, 978, 'Explanation · build the reading habit before optimizing it'),
    segment('TKP18-003', 1205, 1216, 'Disagreement · reject a popular habit claim directly'),
    segment('TKP18-004', 1332, 1350, 'Formulation · the mind should be a servant, not a master'),
    segment('TKP18-005', 1655, 1691, 'Decision rule · one priority beats a fuzzy basket'),
    segment('TKP18-006', 1784, 1826, 'Definition · happiness as the default state'),
    segment('TKP18-007', 1833, 1871, 'Reasoning · every positive contains a negative contrast'),
    segment('TKP18-008', 2373, 2406, 'Formulation · honesty keeps thought and speech aligned'),
    segment('TKP18-009', 2406, 2434, 'Compression · life benefits compound over long time scales'),
    segment('TKP18-010', 2675, 2707, 'Reframing · freedom to → freedom from'),
    segment('TKP18-011', 3401, 3427, 'Reframing · change yourself before changing the world'),
    segment('TKP18-012', 3793, 3816, 'Qualification · future salvation can destroy the present'),
    segment('TKP18-013', 3863, 3890, 'Formulation · nothing exists except this moment'),
    segment('TKP18-014', 3976, 3989, 'Compression · learning is abundant; desire to learn is scarce'),
    segment('TKP18-015', 4405, 4428, 'Definition · science as the study of truth'),
    segment('TKP18-016', 4792, 4818, 'Meta-formulation · distill an insight, then invite attack'),
    segment('TKP18-017', 5122, 5155, 'Decision-making · eliminate what will not work'),
    segment('TKP18-018', 5187, 5208, 'Systems thinking · build environments where success is likely'),
    segment('TKP18-019', 5505, 5532, 'Definition · integrity as an internal moral compass'),
    segment('TKP18-020', 5793, 5814, 'Explanation · real knowledge should become simple'),
    segment('TKP18-021', 5861, 5903, 'Distinction · charlatans complicate; geniuses simplify'),
    segment('TKP18-022', 6030, 6053, 'Formulation · understand basics deeply enough to re-derive'),
    segment('TKP18-023', 6134, 6157, 'Reframing · suffering as a forced moment of truth'),
    segment('TKP18-024', 6193, 6222, 'Decision-making · desire colliding with reality hides truth'),
    segment('TKP18-025', 6385, 6409, 'Qualification · commit for ten years and enjoy the journey'),
    segment('TKP18-026', 6613, 6639, 'Method · try, test, stay skeptical, keep what works'),
    segment('TKP18-027', 6707, 6736, 'Humor + analogy · present self vs heroic future self'),
    segment('TKP18-028', 6882, 6897, 'Self-observation · addicted to the desiring'),
    segment('TKP18-029', 6955, 6984, 'Answer structure · meaning is personal; the question matters'),
    segment('TKP18-030', 7090, 7118, 'Storytelling · Steve Jobs aspiration reversed in one move'),
  ],
}

const navalTimFerriss473: CuratedCollection = {
  id: 'naval-tim-ferriss-473',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'The Tim Ferriss Show #473 · 2020',
  videoId: 'HiYo14wylQw',
  videoTitle: 'Naval Ravikant on Happiness, Reducing Anxiety, and More | The Tim Ferriss Show',
  channelName: 'The Tim Ferriss Show',
  thumbnail: 'https://i.ytimg.com/vi/HiYo14wylQw/hqdefault.jpg',
  duration: 7315,
  description: 'A precise, self-aware Naval on understanding, wealth, anxiety, meditation, relationships, games, and mortality. Especially strong for distinctions, qualification, compression, and turning abstract ideas into memorable language.',
  focus: ['Formulation', 'Articulation', 'Definition', 'Reframing', 'Qualification', 'Thinking aloud'],
  status: 'ready',
  segments: [
    segment('TF473-001', 561, 587, 'Formulation · full-stack intellectual hacker of life'),
    segment('TF473-002', 692, 723, 'Definition · science begins with doubt and falsifiability'),
    segment('TF473-003', 1058, 1083, 'Distinction · memorization vs understanding'),
    segment('TF473-004', 1266, 1292, 'Qualification · jargon compresses knowledge until it replaces understanding'),
    segment('TF473-005', 1318, 1346, 'Method · re-articulate until you truly understand'),
    segment('TF473-006', 1448, 1481, 'Synthesis · complexity emerges from simple rules'),
    segment('TF473-007', 1563, 1583, 'Definition · the purpose of money is freedom'),
    segment('TF473-008', 1719, 1744, 'Compression · productize yourself, then own it'),
    segment('TF473-009', 1768, 1800, 'Definition · suffering is seeing clearly what you avoided'),
    segment('TF473-010', 1867, 1896, 'Reframing · the hard part is unlearning and going back down the mountain'),
    segment('TF473-011', 2243, 2262, 'Formulation · make money with your mind, not your time'),
    segment('TF473-012', 2262, 2283, 'Compression · one good decision multiplied by infinite leverage'),
    segment('TF473-013', 2283, 2306, 'Distinction · 10,000 iterations, not 10,000 hours'),
    segment('TF473-014', 2613, 2641, 'Formulation · calmness under pressure is a superpower'),
    segment('TF473-015', 2764, 2802, 'Definition · meditation as self-examination'),
    segment('TF473-016', 2832, 2863, 'Analogy · the mind as your lifelong crazy roommate'),
    segment('TF473-017', 2863, 2888, 'Reframing · solitude reveals the actual quality of your life'),
    segment('TF473-018', 3155, 3175, 'Thinking aloud · observe unbidden thoughts without identifying with them'),
    segment('TF473-019', 3410, 3434, 'Formulation · solitude makes you self-contained'),
    segment('TF473-020', 3434, 3460, 'Strong ending · when your best hour is alone, the world loses its grip'),
    segment('TF473-021', 3537, 3561, 'Reframing · philosophy should inspire reflection, not become consumption'),
    segment('TF473-022', 3630, 3655, 'Formulation · media makes every problem your problem'),
    segment('TF473-023', 3655, 3678, 'Compression · timeless questions are best answered by old practitioners'),
    segment('TF473-024', 5368, 5396, 'Explanation · digital abundance vs digital scarcity'),
    segment('TF473-025', 5453, 5469, 'Compression · choose long-term over short-term'),
    segment('TF473-026', 5776, 5797, 'Formulation · the best relationships do not feel like work'),
    segment('TF473-027', 6047, 6069, 'Reframing · all of life is games'),
    segment('TF473-028', 6225, 6250, 'Strong ending · win the game so you can be free of it'),
    segment('TF473-029', 6661, 6689, 'Formulation · mortality as a radical freedom reframe'),
    segment('TF473-030', 6689, 6712, 'Reframing · change the worldview that names experience suffering'),
  ],
}

const navalHowToGetRich: CuratedCollection = {
  id: 'naval-how-to-get-rich',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'How to Get Rich · Naval + Nivi · 2019',
  videoId: '1-TZqOsVCNM',
  videoTitle: 'How to Get Rich',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/1-TZqOsVCNM/hqdefault.jpg',
  duration: 12937,
  description: 'The complete Naval + Nivi wealth series in one long-form source. Curated for unusually clean definitions, compressed principles, examples, qualification, and proposition-by-proposition explanation.',
  focus: ['Formulation', 'Compression', 'Explanation', 'Definition', 'Reframing', 'Sentence construction'],
  status: 'ready',
  segments: [
    segment('HTGR-001', 112, 145, 'Definition · wealth is assets that earn while you sleep'),
    segment('HTGR-002', 306, 337, 'Distinction · wealth is positive-sum; status is zero-sum'),
    segment('HTGR-003', 527, 557, 'Reframing · modern abundance proves wealth can be created'),
    segment('HTGR-004', 880, 897, 'Formulation · making money is a learnable skill, not luck'),
    segment('HTGR-005', 1234, 1266, 'Reframing · character turns luck into destiny'),
    segment('HTGR-006', 1361, 1393, 'Explanation · eccentricity helps you reach uncrowded frontiers'),
    segment('HTGR-007', 1458, 1490, 'Distinction · rented time ties inputs directly to outputs'),
    segment('HTGR-008', 2108, 2142, 'Explanation · the internet gives every niche obsession scale'),
    segment('HTGR-009', 2336, 2369, 'Analogy · all major returns in life compound'),
    segment('HTGR-010', 2562, 2594, 'Formulation · long-term games bake the pie together'),
    segment('HTGR-011', 2689, 2721, 'Framework · intelligence, energy, integrity'),
    segment('HTGR-012', 3035, 3068, 'Instruction · action bias plus rational optimism'),
    segment('HTGR-013', 3339, 3373, 'Definition · the most interesting knowledge cannot be taught'),
    segment('HTGR-014', 3465, 3498, 'Explanation · genuine curiosity leads to specific knowledge'),
    segment('HTGR-015', 3584, 3617, 'Formulation · what feels like play to you can look like work to others'),
    segment('HTGR-016', 4098, 4129, 'Synthesis · builder + seller is the magic combination'),
    segment('HTGR-017', 6139, 6155, 'Compression · code and media are permissionless leverage'),
    segment('HTGR-018', 7456, 7488, 'Definition · judgment and wisdom are long-term consequence prediction'),
    segment('HTGR-019', 8427, 8443, 'Formulation · a busy calendar and busy mind destroy great work'),
    segment('HTGR-020', 8460, 8491, 'Reframing · redefine what you do until you can be number one'),
    segment('HTGR-021', 9345, 9378, 'Method · listen broadly, then build your own point of view'),
    segment('HTGR-022', 9444, 9478, 'Analogy · maxims are mental pointers to lived principles'),
    segment('HTGR-023', 10708, 10741, 'Reframing · ethics as long-term greedy'),
    segment('HTGR-024', 11407, 11425, 'Instruction · act like the owner until you become the owner'),
    segment('HTGR-025', 11490, 11523, 'Decision rule · avoid ruin before optimizing upside'),
    segment('HTGR-026', 12216, 12247, 'Qualification · rent your time only while learning and saving'),
    segment('HTGR-027', 12343, 12374, 'Instruction · choose the steepest learning curve over repetitive drudgery'),
  ],
}

const navalSmartFriendsBuildingWealth: CuratedCollection = {
  id: 'naval-smart-friends-building-wealth',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Smart Friends · Building Wealth · 2025',
  videoId: 'fEPkweR086A',
  videoTitle: 'My Conversation with Naval on Building Wealth',
  channelName: 'Eric Jorgenson',
  thumbnail: 'https://i.ytimg.com/vi/fEPkweR086A/hqdefault.jpg',
  duration: 2275,
  description: 'A compact 2025 update to Naval’s wealth thinking: assets, knowledge, ethical capitalism, optimism, small-group competition, hard-to-vary products, and technology. Curated for formulation, clean conceptual pivots, analogy, and explanation.',
  focus: ['Formulation', 'Articulation', 'Definition', 'Analogy', 'Reframing', 'Explanation'],
  status: 'ready',
  segments: [
    segment('SFBW-001', 86, 111, 'Formulation · escape the input-tied-to-output trap'),
    segment('SFBW-002', 114, 131, 'Reframing · laziness as leverage and efficiency'),
    segment('SFBW-003', 303, 333, 'Analogy · gold points to value; people create value'),
    segment('SFBW-004', 399, 434, 'Distinction · wisdom must be recreated inside the listener'),
    segment('SFBW-005', 487, 510, 'Analogy · unpack a nursery rhyme into a life philosophy'),
    segment('SFBW-006', 578, 603, 'Reframing · timeless topics inevitably become clichés'),
    segment('SFBW-007', 666, 704, 'Analogy · slicing the pie versus baking the pie'),
    segment('SFBW-008', 764, 791, 'Qualification · capitalism, externalities, and human flourishing'),
    segment('SFBW-009', 805, 839, 'Reframing · stop treating the whole game as rigged'),
    segment('SFBW-010', 899, 927, 'Strong ending · possibility precedes long-term success'),
    segment('SFBW-011', 927, 963, 'Explanation · optimism grounded in good explanations'),
    segment('SFBW-012', 1028, 1066, 'Analogy · everyone improving their life is a little scientist'),
    segment('SFBW-013', 1070, 1112, 'Synthesis · science, business, and evolution share one filtering pattern'),
    segment('SFBW-014', 1115, 1152, 'Definition · ethical risk means bearing your own consequences'),
    segment('SFBW-015', 1246, 1284, 'Qualification · morality is easy from outside the arena'),
    segment('SFBW-016', 1313, 1340, 'Distinction · groups seek consensus; individuals can seek truth'),
    segment('SFBW-017', 1340, 1378, 'Explanation · small groups need skin in the game and competition'),
    segment('SFBW-018', 1474, 1507, 'Reframing · alignment becomes coercion when strangers must agree'),
    segment('SFBW-019', 1688, 1710, 'Definition · a hard-to-vary product cannot change without breaking'),
    segment('SFBW-020', 1710, 1740, 'Analogy · puzzle pieces explain hard-to-vary design'),
    segment('SFBW-021', 1781, 1810, 'Reframing · constraints can create higher-order capability'),
    segment('SFBW-022', 1810, 1844, 'Explanation · creation requires voluntary constraints'),
    segment('SFBW-023', 1846, 1874, 'Definition · elegance means nothing unnecessary remains'),
    segment('SFBW-024', 1897, 1930, 'Compression · technology automates, scales, and distributes knowledge'),
    segment('SFBW-025', 2013, 2040, 'Explanation · great products have surprising reach'),
    segment('SFBW-026', 2166, 2200, 'Reframing · the internet destroys the mediocre middle'),
    segment('SFBW-027', 2194, 2225, 'Explanation · scale economies make the best technology broadly accessible'),
  ],
}

const navalTimFerriss97: CuratedCollection = {
  id: 'naval-tim-ferriss-97',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'The Tim Ferriss Show #97 · 2015',
  videoId: '-7J-Gwc9pVg',
  videoTitle: 'The Person I Call Most for Startup Advice - Naval Ravikant',
  channelName: 'Tim Ferriss',
  thumbnail: 'https://i.ytimg.com/vi/-7J-Gwc9pVg/hqdefault.jpg',
  duration: 8037,
  description: 'Naval’s first Tim Ferriss appearance: an unusually rich early snapshot of his thinking on happiness, honesty, integrity, reading, attention, self-observation, commitment, time, and desire. Curated primarily for memorable formulation and complete trainable thoughts.',
  focus: ['Formulation', 'Articulation', 'Reframing', 'Integrity', 'Self-observation', 'Reading'],
  status: 'ready',
  segments: [
    segment('TF97-001', 447, 489, 'Reframing · humans are meant for changing problems, not repetitive specialization'),
    segment('TF97-002', 641, 679, 'Distinction · success intensity and happiness pull in opposite directions'),
    segment('TF97-003', 679, 713, 'Reframing · comparison-driven success quietly manufactures unhappiness'),
    segment('TF97-004', 713, 748, 'Formulation · happiness is internal, chosen, and trainable'),
    segment('TF97-005', 1082, 1126, 'Formulation · Feynman-style honesty means refusing to fool yourself'),
    segment('TF97-006', 1166, 1206, 'Explanation · dishonesty creates a second mental thread you must maintain'),
    segment('TF97-007', 1396, 1431, 'Reframing · the information revolution reverses the logic of the industrial firm'),
    segment('TF97-008', 1515, 1541, 'Formulation · humans are built to work for themselves, not inside hierarchies'),
    segment('TF97-009', 1584, 1628, 'Framework · intelligence and energy are necessary but not sufficient'),
    segment('TF97-010', 1628, 1666, 'Definition · intelligence plus energy without integrity creates a smart crook'),
    segment('TF97-011', 1666, 1709, 'Decision rule · unfairness toward others predicts future unfairness toward you'),
    segment('TF97-012', 1709, 1745, 'Formulation · scarce time and mental energy matter more than money'),
    segment('TF97-013', 1956, 1999, 'Reframing · being right when everyone disagrees is where the payoff lives'),
    segment('TF97-014', 2618, 2654, 'Reframing · old human problems often have older, time-tested solutions'),
    segment('TF97-015', 2686, 2728, 'Method · treat books like disposable posts so curiosity can beat completion'),
    segment('TF97-016', 2812, 2849, 'Distinction · more facts can leave you with no more wisdom'),
    segment('TF97-017', 3631, 3676, 'Definition · the real winners step out of the status game entirely'),
    segment('TF97-018', 3810, 3837, 'Definition · enlightenment as the space between thoughts'),
    segment('TF97-019', 3964, 4001, 'Self-observation · watch fear clearly and it begins to dissolve'),
    segment('TF97-020', 4918, 4958, 'Reframing · saying “I’ll try” often disguises postponement'),
    segment('TF97-021', 4958, 4998, 'Instruction · external commitment removes the escape hatch'),
    segment('TF97-022', 4998, 5039, 'Qualification · choose a smaller honest change when you are not ready for total change'),
    segment('TF97-023', 5769, 5799, 'Analogy · live as the star of the movie of your own life'),
    segment('TF97-024', 5945, 5985, 'Self-observation · most waking thought is a dream you can catch yourself inside'),
    segment('TF97-025', 6038, 6071, 'Meta-formulation · use a written vocabulary while speaking'),
    segment('TF97-026', 6313, 6349, 'Reframing · freedom to skip and abandon books makes reading sustainable'),
    segment('TF97-027', 6655, 6688, 'Formulation · learning how to learn is the ultimate meta-skill'),
    segment('TF97-028', 6751, 6775, 'Instruction · be yourself, say no more, and protect your finite time'),
    segment('TF97-029', 7526, 7569, 'Definition · desire is a contract to be unhappy until you get what you want'),
    segment('TF97-030', 7610, 7640, 'Framework · change it, accept it, or leave it'),
  ],
}

const navalAfterOnEndGames1: CuratedCollection = {
  id: 'naval-after-on-end-games-1',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'After On · End Games · Part 1 · 2019',
  videoId: 'brUC8Vh2gms',
  videoTitle: '44: End Games (part 1) | Naval Ravikant',
  channelName: 'After On Podcast',
  thumbnail: 'https://i.ytimg.com/vi/brUC8Vh2gms/hqdefault.jpg',
  duration: 4423,
  description: 'Naval with Rob Reid on existential risk, destructive-power asymmetry, drones, AI, incentives, and civilization-scale technological risk. Curated conservatively from the official timestamped transcript, prioritizing complete trainable thoughts with auditable boundaries.',
  focus: ['Formulation', 'Articulation', 'Analogy', 'Risk', 'Incentives', 'Qualification'],
  status: 'ready',
  segments: [
    segment('AOEG1-001', 865, 902, 'Reframing · overestimate technology in the short run, underestimate it in the long run'),
    segment('AOEG1-002', 971, 1002, 'Distinction · destructive capability arrives before safe, scalable creation'),
    segment('AOEG1-003', 1096, 1137, 'Analogy · drones become guided bullets as targeting gets cheaper'),
    segment('AOEG1-004', 1389, 1401, 'Reframing · technological scrutiny eventually reaches heads of state too'),
    segment('AOEG1-005', 1650, 1688, 'Qualification · Pascal’s wager fails when humans reason badly about infinities'),
    segment('AOEG1-006', 1807, 1819, 'Compression · privatized gains and socialized losses distort existential-risk incentives'),
    segment('AOEG1-007', 1946, 1979, 'Explanation · incentives shape expert judgment; seek disinterested observers'),
    segment('AOEG1-008', 2892, 2918, 'Analogy · infer how AI may treat us from how humans treat weaker creatures'),
    segment('AOEG1-009', 3045, 3067, 'Qualification · even a benevolent superintelligence could reduce humans to irrelevance'),
    segment('AOEG1-010', 3452, 3465, 'Formulation · taming nature may eventually imply possessing the power to end it'),
    segment('AOEG1-011', 3598, 3627, 'Historical example · technical capability plus state incentives can cross moral lines'),
  ],
}

const navalSellTheTruth: CuratedCollection = {
  id: 'naval-sell-the-truth-2026',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Sell the Truth · Naval + Nivi · 2026',
  videoId: 'l1DQgwomzxU',
  videoTitle: 'Sell the Truth',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/l1DQgwomzxU/hqdefault.jpg',
  duration: 1660,
  description: 'Naval and Nivi on persuasion, credibility, rational empathy, charisma, leadership, motivation, dealmaking, optionality, and nonlinear returns. Curated conservatively from the official full transcript plus YouTube-linked timestamp anchors, prioritizing formulation and exact trainable boundaries.',
  focus: ['Formulation', 'Articulation', 'Persuasion', 'Reframing', 'Dealmaking', 'Qualification'],
  status: 'ready',
  segments: [
    segment('STT-001', 226, 254, 'Disagreement · understand the reason first; disagreement is where humility arrives'),
    segment('STT-002', 254, 271, 'Reframing · “yes, and” as rational empathy, not a persuasion trick'),
    segment('STT-003', 279, 316, 'Definition · objectivity means removing ego and reasoning from the other perspective'),
    segment('STT-004', 316, 337, 'Qualification · selfish honesty because being wrong is the default risk'),
    segment('STT-005', 909, 930, 'Formulation · if you aren’t genuinely excited, what are you doing selling it?'),
    segment('STT-006', 1120, 1137, 'Decision rule · if it feels like selling, you’re probably selling the wrong thing'),
    segment('STT-007', 1278, 1301, 'Decision rule · plan early enough that every deal remains walk-away optional'),
    segment('STT-008', 1301, 1331, 'Analogy · even marriage can unwind more easily than some bad business deals'),
    segment('STT-009', 1331, 1372, 'Definition · a contract trades future optionality for coordinated value creation'),
    segment('STT-010', 1372, 1419, 'Qualification · optionality is powerful; compromise can quietly trap great businesses'),
    segment('STT-011', 1648, 1660, 'Strong ending · live several different lives inside this one'),
  ],
}

const navalDeutschKnowledge2: CuratedCollection = {
  id: 'naval-deutsch-knowledge-2',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'David Deutsch · Knowledge Creation and the Human Race · Part 2 · 2023',
  videoId: 'aQfeYBa1MTk',
  videoTitle: 'David Deutsch: Knowledge Creation and The Human Race, Part 2',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/aQfeYBa1MTk/hqdefault.jpg',
  duration: 2040,
  description: 'Naval with David Deutsch and Brett Hall on Popper, creative conjecture, experiments, physical computation, self-refuting theories, technological progress, misinformation, and knowledge across the multiverse. Curated from Naval’s official full transcript and a dense transcript layer aligned to the official YouTube timebase.',
  focus: ['Formulation', 'Articulation', 'Epistemology', 'Distinction', 'Synthesis', 'Reframing'],
  status: 'ready',
  segments: [
    segment('DDK2-001', 151, 183, 'Formulation · creative guesses change how you see the world'),
    segment('DDK2-002', 426, 459, 'Distinction · experiment vs demonstration vs measurement'),
    segment('DDK2-003', 554, 573, 'Synthesis · computation and mathematics remain bound to physical context'),
    segment('DDK2-004', 625, 649, 'Reframing · the precautionary principle can refute itself'),
    segment('DDK2-005', 1159, 1187, 'Analogy · obsolete technologies can still be necessary steps toward truth'),
    segment('DDK2-006', 1784, 1825, 'Disagreement · misinformation demands rival theories, reversibility, and open debate'),
    segment('DDK2-007', 1832, 1856, 'Definition · knowledge causes itself to be replicated in the environment'),
    segment('DDK2-008', 1856, 1873, 'Explanation · useful ideas and genes get copied because they work'),
    segment('DDK2-009', 1873, 1902, 'Synthesis · useful knowledge converges across the multiverse'),
    segment('DDK2-010', 1902, 1923, 'Analogy · a crystal of knowledge makes truth visible as convergence'),
    segment('DDK2-011', 2020, 2040, 'Strong ending · knowledge creates nonlinearities yet remains creative and conjectural'),
  ],
}

const navalDeutschFiles1: CuratedCollection = {
  id: 'naval-deutsch-files-1',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'The Deutsch Files I · 2024',
  videoId: 'NI1l94sT4oc',
  videoTitle: 'The Deutsch Files I',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/NI1l94sT4oc/hqdefault.jpg',
  duration: 3292,
  description: 'Naval and Brett Hall in free-form conversation with David Deutsch on ChatGPT, creativity, personhood, life philosophy, Taking Children Seriously, relationships, and civilizational confidence. Curated from Naval’s official full transcript and a dense transcript layer aligned to the official YouTube timebase; selection is intentionally tight because Naval is often the questioner rather than the primary explainer.',
  focus: ['Formulation', 'Articulation', 'Question framing', 'Synthesis', 'Reframing', 'Distinction'],
  status: 'ready',
  segments: [
    segment('DF1-001', 309, 333, 'Analogy · Borges changes one rule then follows every logical consequence'),
    segment('DF1-002', 642, 669, 'Steelman · emergent algorithms as the strongest case for model understanding'),
    segment('DF1-003', 677, 702, 'Question framing · multimodal embodiment as the baby-learning argument'),
    segment('DF1-004', 813, 849, 'Formulation · creativity is more than remixing; humans make narrow leaps through vast search spaces'),
    segment('DF1-005', 849, 870, 'Explanation · risky conjectures cut through an almost infinite search space'),
    segment('DF1-006', 983, 1010, 'Synthesis · bounded formal systems cannot contain unbounded creativity'),
    segment('DF1-007', 1010, 1032, 'Counterargument · language combinatorics as a case for social creativity'),
    segment('DF1-008', 1253, 1274, 'Critique · fluent verbiage can add no information and lose what matters'),
    segment('DF1-009', 1274, 1297, 'Distinction · extrapolation is easy; synthesis requires separating core from superfluous'),
    segment('DF1-010', 1927, 1968, 'Question framing · derive a life philosophy from error correction, optimism, and fun'),
    segment('DF1-011', 2232, 2264, 'Reframing · Taking Children Seriously as a test for taking adults seriously'),
    segment('DF1-012', 3254, 3270, 'Compression · ideology persists until consequences become real and cascades reverse'),
  ],
}

const navalDeutschFiles2: CuratedCollection = {
  id: 'naval-deutsch-files-2',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'The Deutsch Files II · 2024',
  videoId: 'I6GNK6BR4E8',
  videoTitle: 'The Deutsch Files II',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/I6GNK6BR4E8/hqdefault.jpg',
  duration: 4468,
  description: 'Naval and Brett Hall continue with David Deutsch across computation, epistemology, evolution, quantum theory, knowledge, optimism, constructor theory, and individual agency. Curated from Naval’s official full transcript plus a dense timestamped transcript aligned to the full recording; selection intentionally favors Naval’s own synthesis, clarification, and question framing over guest-heavy exposition.',
  focus: ['Formulation', 'Articulation', 'Synthesis', 'Question framing', 'Clarification', 'Analogy'],
  status: 'ready',
  segments: [
    segment('DF2-001', 0, 21, 'Question framing · open the four strands by asking what even experts fail to appreciate'),
    segment('DF2-002', 1336, 1349, 'Distinction · instruments inherit problems from outside rather than generating their own'),
    segment('DF2-003', 2068, 2080, 'Synthesis · knowledge, wealth, optimism, error correction, and fun converge on universal explanation'),
    segment('DF2-004', 2391, 2424, 'Clarification · restate emergence as equally valid higher-level explanation'),
    segment('DF2-005', 2788, 2809, 'Synthesis · problem → creative solution → knowledge → causal replication'),
    segment('DF2-006', 2813, 2833, 'Analogy · knowledge propagates through the multiverse like a growing crystal'),
    segment('DF2-007', 2854, 2871, 'Qualification · knowledge only exists relative to the problem it actually solves'),
    segment('DF2-008', 3051, 3071, 'Synthesis · the right problems plus solutions grow both knowledge and wealth'),
    segment('DF2-009', 3377, 3390, 'Compression · the inanimate universe has immense scale but little diversity of knowledge'),
    segment('DF2-010', 3390, 3414, 'Synthesis · evolution creates knowledge slowly; human creativity accelerates it dramatically'),
    segment('DF2-011', 3415, 3431, 'Formulation · universal explainers stand at the beginning of an infinity of knowledge'),
    segment('DF2-012', 3672, 3699, 'Reframing · timeless explanation beats reducing reality to initial conditions'),
    segment('DF2-013', 4205, 4227, 'Question framing · translate the four strands into a better life and a better world'),
  ],
}

const mikeGirlfriendsBoyfriend: CuratedCollection = {
  id: 'mike-birbiglia-girlfriends-boyfriend',
  speakerId: 'mike-birbiglia',
  speaker: 'Mike Birbiglia',
  sourceTitle: "My Girlfriend's Boyfriend · Full Show",
  videoId: '29LxAwlGTpk',
  videoTitle: "Mike Birbiglia: My Girlfriend's Boyfriend (Full Show)",
  channelName: 'Punchline',
  thumbnail: 'https://i.ytimg.com/vi/29LxAwlGTpk/hqdefault.jpg',
  duration: 4555,
  description: 'A long-form performed show selected for story structure, personal detail, calm delivery, callbacks, and emotional payoff. The practice set follows a complete arc: attraction, revelation, escalation, physical stakes, and a quiet resolution. Transcript snippets are anchored to a public timecoded transcript of the same special and kept short for shadowing.',
  focus: ['Story framing', 'Personal detail', 'Calm delivery', 'Perspective shifts', 'Callbacks', 'Emotional payoff'],
  status: 'ready',
  segments: [
    segmentWithLines('MGB-001', 2479, 2511, 'Story framing · first love as a story engine', [
      transcriptLine('I remember the first time I fell in love.', 2479, 5),
      transcriptLine("I was in high school, and it was that first time where you fall up and you're just like, 'This is it.'", 2480, 13),
      transcriptLine("I'm seventeen years old and I'm done.", 2484, 9),
      transcriptLine('Her name was Amanda, and she was adorable and funny.', 2493, 16),
    ]),
    segmentWithLines('MGB-002', 2551, 2598, 'Character detail · establish a person through specific red flags', [
      transcriptLine('I find that when you fall in love, you tend to overlook certain red flags.', 2551, 17),
      transcriptLine('One of them was that she would say really mean stuff to me, but then she would pull it back.', 2551, 17),
      transcriptLine("She'd be like, 'No one likes you at all—only kidding.'", 2568, 21),
      transcriptLine('The second red flag with Amanda was that she was a liar.', 2589, 23),
    ]),
    segmentWithLines('MGB-003', 2695, 2752, 'Reveal · let the audience realize the situation one step after you do', [
      transcriptLine('She said she had another boyfriend at home, but they were in the process of breaking up.', 2695, 14),
      transcriptLine('It was a bad time because his parents were sick, so I tried to be understanding.', 2695, 14),
      transcriptLine("She invited me to meet her parents, and I thought, 'This is the affirmation that I need.'", 2695, 14),
      transcriptLine("I'm going to be crowned as the main boyfriend.", 2709, 5),
      transcriptLine('A few hours go by, and this other guy comes over. His name is Scott.', 2714, 24),
      transcriptLine("Slowly I'm noticing similarities between Scott and things Amanda has said about her other boyfriend.", 2738, 3),
      transcriptLine("They're both in their first year in college and they're competitive wrestlers.", 2741, 11),
      transcriptLine("And it's dawning on me that I'm hanging out with my girlfriend's boyfriend.", 2741, 11),
    ]),
    segmentWithLines('MGB-004', 2765, 2800, 'Perspective shift · hold compassion and absurdity in the same frame', [
      transcriptLine('I could totally see what she saw in him.', 2765, 12),
      transcriptLine('There\'s some consolation that when he would go in the other room, she would hold on to my hand and say, “I wish it were just you and me here.”', 2765, 16),
      transcriptLine('I remember thinking, “You could make that happen.”', 2781, 7),
      transcriptLine("The way she said it was as though she weren't involved in the decision process.", 2788, 4),
    ]),
    segmentWithLines('MGB-005', 2800, 2846, 'Emotional contradiction · anger, then the urge to make a good impression', [
      transcriptLine('The day took an even stranger turn when Scott suggested that we go hang out at his house and I met his parents.', 2800, 20),
      transcriptLine("It is indescribable meeting your girlfriend's boyfriend's parents for the first time.", 2800, 20),
      transcriptLine('Part of you is angry for obvious reasons, but then part of you still wants to make a good impression.', 2823, 6),
      transcriptLine("Maybe if this goes well, she'll see that I'm good with adults in general.", 2831, 11),
      transcriptLine('At one point, his dad even said to me, “How do you know Amanda?”', 2842, 4),
    ]),
    segmentWithLines('MGB-006', 3710, 3755, 'Escalation · move from an internal argument to a physical event', [
      transcriptLine('This relationship is messing up my entire life.', 3710, 4),
      transcriptLine('I know I\'m right. I gotta tell her about this in the morning.', 3714, 5),
      transcriptLine("I drive out of Andy's small road and, in one and a half seconds, I spun around.", 3719, 15),
      transcriptLine('I think I\'m dead. No, wait, I\'m paralyzed. And then I hear nothing.', 3734, 7),
      transcriptLine('Twenty minutes later, I\'m sitting on the curb. That\'s when I start crying.', 3741, 14),
    ]),
    segmentWithLines('MGB-007', 3776, 3819, 'Vulnerability · make the stakes physical without forcing the emotion', [
      transcriptLine("I'm looking at my totaled car in front of me and realizing that, in that moment, I might have ceased to exist.", 3776, 22),
      transcriptLine("I don't really believe in anything, so in my mind, that would have been the end of all things I'd experienced in my life.", 3798, 21),
      transcriptLine('Every kiss or failed kiss, or Scrambler ride, would have come to a conclusion.', 3798, 21),
      transcriptLine('The officer comes over and he says, “What happened?”', 3798, 21),
    ]),
    segmentWithLines('MGB-008', 4278, 4324, 'Resolution · release the argument for the relationship', [
      transcriptLine("Jenny says, 'Mike, you're right, but it's only hurting you.'", 4278, 23),
      transcriptLine("I'm so glad that you're alive, and I think that we should focus on that.", 4301, 4),
      transcriptLine('She only has to say it once and I give up the case and I pay for this guy\'s car.', 4301, 4),
      transcriptLine('July 7, 2007, Jenny and I went to City Hall and got married.', 4324, 4),
      transcriptLine("I still don't believe in the idea of marriage, but I believe in her, and I've given up on the idea of being right.", 4324, 4),
    ]),
  ],
}

const mikeWhatIShouldHaveSaid: CuratedCollection = {
  id: 'mike-birbiglia-what-i-should-have-said',
  speakerId: 'mike-birbiglia',
  speaker: 'Mike Birbiglia',
  sourceTitle: 'What I Should Have Said Was Nothing · Full Show',
  videoId: 'FQ0OE6dz5yI',
  videoTitle: 'Mike Birbiglia: What I Should Have Said Was Nothing (Full Show)',
  channelName: 'Punchline',
  thumbnail: 'https://i.ytimg.com/vi/FQ0OE6dz5yI/hqdefault.jpg',
  duration: 3394,
  description: 'A full performed show selected for premise, specific detail, character voice, escalation, callbacks, and emotional recovery. These short practice clips use the exact upload\'s timestamped English caption layer and favor complete, shadowable thoughts over the show\'s longer routines.',
  focus: ['Premise', 'Specific detail', 'Character voice', 'Escalation', 'Callbacks', 'Emotional recovery'],
  status: 'ready',
  segments: [
    segmentWithLines('WSN-001', 39, 99, 'Premise · establish a true story and let the audience lean in', [
      transcriptLine("I'm going to tell you some stories tonight from my secret public journal, which is a blog that I write.", 39, 24),
      transcriptLine('The stories I tell are true.', 69, 7),
      transcriptLine('I always have people come up to me after shows and ask, “Was that true?”', 69, 18),
      transcriptLine("I guess I could say it louder: yeah, it's probably true.", 87, 11),
    ]),
    segmentWithLines('WSN-002', 103, 160, 'Specific detail · turn a family habit into a shared phrase', [
      transcriptLine("I love them, but if I met them at a party and they were strangers, I'd just be like, ‘These people.’", 103, 20),
      transcriptLine("They're older, more boring versions of me.", 123, 10),
    ]),
    segmentWithLines('WSN-003', 160, 190, 'Language · decode a private family phrase in public', [
      transcriptLine('They make up phrases.', 164, 6),
      transcriptLine('My mother would say, “Like, funny at doing that.”', 164, 16),
      transcriptLine('I decoded it. I realized that “fun” was her way of saying “hell.”', 174, 12),
    ]),
    segmentWithLines('WSN-004', 453, 515, 'Escalation · stack specific images on one absurd premise', [
      transcriptLine("I didn't realize how good I was with computers until I met my parents.", 453, 16),
      transcriptLine('If a stranger emails you an attachment, you should not open it because you can get a virus.', 453, 24),
      transcriptLine('They ended up with a porn virus on their computer.', 483, 13),
      transcriptLine('The icons became dildos.', 515, 7),
    ]),
    segmentWithLines('WSN-005', 515, 575, 'Aftermath · extend the image until the object has a point of view', [
      transcriptLine('The icons became dildos.', 515, 7),
      transcriptLine('A guy jumped out of the screen and was like, “Where is your daughter?”', 522, 17),
      transcriptLine('They placed the computer in the corner with the screen facing the wall, like the computer had done something wrong.', 555, 20),
    ]),
    segmentWithLines('WSN-006', 1046, 1105, 'Character voice · give an internal voice a physical point of view', [
      transcriptLine("I feel like when I go to bed at night, it's like a different human being enters my body for the night shift.", 1046, 24),
      transcriptLine('I call my guy Sleepy Carl.', 1069, 8),
      transcriptLine("He's a terrible employee, but he's a great dude.", 1069, 13),
      transcriptLine('Why would you go out there when you can stay here, ride on a Ferris wheel, and make a pizza?', 1087, 18),
    ]),
    segmentWithLines('WSN-007', 2115, 2174, 'Callback · let one phrase define the whole performance', [
      transcriptLine("I'm very awkward, and I have a habit of making awkward situations even more awkward.", 2115, 24),
      transcriptLine('Now, what I should have said was nothing.', 2145, 9),
      transcriptLine('What I did say was, “You’d be surprised.”', 2145, 14),
      transcriptLine("I don't have an on-deck circle for ideas. It's just batter up.", 2159, 15),
    ]),
    segmentWithLines('WSN-008', 2632, 2675, 'Recovery · button a failure with generosity and a final turn', [
      transcriptLine('At that point, I threw in the towel. I thanked the audience and apologized simultaneously.', 2632, 25),
      transcriptLine('Joe, we are leaving this place now.', 2660, 8),
      transcriptLine('Because everybody left, my odds are amazing.', 2668, 7),
    ]),
  ],
}

const mikeThirtyMinutesGirlfriendsBoyfriend: CuratedCollection = {
  id: 'mike-birbiglia-30-minutes-girlfriends-boyfriend',
  speakerId: 'mike-birbiglia',
  speaker: 'Mike Birbiglia',
  sourceTitle: "30 Minutes of My Girlfriend's Boyfriend",
  videoId: 'DVLomO81nbE',
  videoTitle: "Mike Birbiglia: 30 Minutes of My Girlfriend's Boyfriend",
  channelName: 'Comedy Dynamics',
  thumbnail: 'https://i.ytimg.com/vi/DVLomO81nbE/hqdefault.jpg',
  duration: 1823,
  description: 'A tighter performed cut built around precision, romantic awkwardness, delayed realization, and physical escalation. The practice set stays with self-contained beats from the exact upload\'s timestamped English caption layer.',
  focus: ['Precision', 'Act-outs', 'Romantic awkwardness', 'Delayed realization', 'Red flags', 'Physical escalation'],
  status: 'ready',
  segments: [
    segmentWithLines('MGB30-001', 31, 84, 'Act-out · turn a physical detail into character', [
      transcriptLine("I've given up on having a traditional male physique, so now I'm going for ‘strong independent woman.’", 31, 19),
      transcriptLine("Sometimes I'll skip whole sections of the difficult exercises when the instructor isn't looking.", 62, 22),
    ]),
    segmentWithLines('MGB30-002', 84, 140, 'Act-out · make the audience see the pose before the narrator explains it', [
      transcriptLine('When she looks over, I always have to strike a pose as though I have been doing what everybody else has been doing.', 84, 26),
      transcriptLine('It reminds me of the Olympics.', 110, 10),
    ]),
    segmentWithLines('MGB30-003', 223, 283, 'Romantic framing · make rejection concrete', [
      transcriptLine('For a moment in the back seat, it felt like we were holding up two halves of a broken paper heart.', 223, 22),
      transcriptLine('I offered to walk her to her room, and she said, “Sure.”', 246, 13),
      transcriptLine('I think we should connect mouths.', 259, 8),
      transcriptLine('Those are two very different mouth agendas.', 267, 9),
    ]),
    segmentWithLines('MGB30-004', 360, 420, 'Precision · build a comic category with a clean list', [
      transcriptLine('There was the make-out club and the non-make-out club.', 360, 18),
      transcriptLine('First order of business: Nintendo. Second order of business: why does nobody like us?', 388, 22),
    ]),
    segmentWithLines('MGB30-005', 426, 490, 'Callback · turn a tiny phone detail into a long-running premise', [
      transcriptLine('She had to talk to me on the phone every night about homework, thanks to alphabetical order.', 426, 23),
      transcriptLine('Mike, you have to stop. I am going to pee myself.', 458, 17),
    ]),
    segmentWithLines('MGB30-006', 933, 996, 'Perspective shift · let the audience see the red flag after the narrator', [
      transcriptLine('She was a delinquent, and I thought that was a really strong quality.', 933, 19),
      transcriptLine('I wanted to do things people write articles about.', 969, 12),
    ]),
    segmentWithLines('MGB30-007', 996, 1060, 'Red flags · name the pattern only after the story has earned it', [
      transcriptLine('When you fall in love, you tend to overlook certain red flags.', 996, 15),
      transcriptLine('The Jedi level of lying is when you lie about little stuff and nobody notices when you are lying about big stuff.', 1024, 23),
    ]),
    segmentWithLines('MGB30-008', 1167, 1230, 'Reveal · delay the conclusion by one beat', [
      transcriptLine("And it's dawning on me that I'm hanging out with my girlfriend's boyfriend.", 1167, 14),
      transcriptLine("It is indescribable meeting your girlfriend's boyfriend's parents for the first time.", 1209, 21),
    ]),
    segmentWithLines('MGB30-009', 1535, 1600, 'Physical escalation · make a confident argument collapse into a beat', [
      transcriptLine('She sounds crazy, even if what she is saying is not that crazy.', 1535, 16),
      transcriptLine("I know I'm right. I have to tell her about this in the morning.", 1559, 12),
      transcriptLine("In one and a half seconds, I'm spun around.", 1571, 10),
      transcriptLine("I think I'm dead. No, wait, I'm paralyzed. And then I hear nothing.", 1581, 17),
    ]),
  ],
}

const mikeThisAmericanLifeLive: CuratedCollection = {
  id: 'mike-birbiglia-this-american-life-live',
  speakerId: 'mike-birbiglia',
  speaker: 'Mike Birbiglia',
  sourceTitle: 'This American Life · Live at BAM',
  videoId: '1x1iL8cNqiw',
  videoTitle: 'Mike Birbiglia - This American Life - Live at BAM',
  channelName: 'This American Life',
  thumbnail: 'https://i.ytimg.com/vi/1x1iL8cNqiw/hqdefault.jpg',
  duration: 671,
  description: 'A compact live story with unusually clear presentation architecture: premise, escalation, physical action, and a callback ending. The clips use the exact performance\'s timestamped English caption layer and are kept short enough to rehearse as a story unit.',
  focus: ['Premise', 'Escalation', 'Physical narration', 'Story stakes', 'Callbacks', 'Ending'],
  status: 'ready',
  segments: [
    segmentWithLines('BAM-001', 59, 119, 'Premise · normalize a strange domestic detail before escalating', [
      transcriptLine('My favorite thing about being married is that you can share jokes with your wife or husband that are funny to you.', 59, 24),
      transcriptLine('When you have a cat, your barometer for humor is out the window.', 83, 16),
      transcriptLine('I called Massachusetts “Catsachusetts,” which is not funny, but in our house was the joke of the year.', 99, 20),
    ]),
    segmentWithLines('BAM-002', 119, 180, 'Relationship stakes · let a tiny mistake reveal the whole marriage', [
      transcriptLine('My wife asked me to acclimate Ivan to the bedroom.', 125, 15),
      transcriptLine('My wife gave me a look I can only describe as divorce eyes.', 153, 18),
      transcriptLine('Before that point, I was convinced we would be married forever.', 171, 9),
    ]),
    segmentWithLines('BAM-003', 180, 240, 'Escalation · make the relationship stake visible inside an absurd search', [
      transcriptLine('There were parasitic mice in the house.', 183, 10),
      transcriptLine('A mouse was watching TV also.', 214, 10),
      transcriptLine('I do not like this show either.', 224, 8),
    ]),
    segmentWithLines('BAM-004', 310, 370, 'Rule · establish a shared agreement, then make the scene physical', [
      transcriptLine('We have a cat. We do everything for the cat.', 310, 15),
      transcriptLine('We have a gentleman’s agreement that if a mouse should walk in that door, he will kill that mouse.', 328, 25),
      transcriptLine('We will never speak of that mouse again.', 353, 12),
    ]),
    segmentWithLines('BAM-005', 370, 400, 'Button · land the rule with a compact reference', [
      transcriptLine("That's from Catfather.", 379, 8),
    ]),
    segmentWithLines('BAM-006', 456, 510, 'Physical payoff · make the action legible through clean narration', [
      transcriptLine('I have a serious sleepwalking disorder, so I am not even really sure it is happening.', 456, 21),
      transcriptLine('I put a cup over the mouse and take it into the backyard.', 490, 15),
      transcriptLine('I put the mouse into the forest, where I can only assume that he walked into the mouth of a wolf.', 497, 13),
    ]),
    segmentWithLines('BAM-007', 531, 574, 'Callback · repeat the opening phrase with a transformed meaning', [
      transcriptLine('A few minutes ago I prefaced the story with a Massachusetts-based pun.', 531, 17),
      transcriptLine('I concluded the story with another Massachusetts-based pun that was nearly identical.', 548, 17),
      transcriptLine('We applauded it, which means in a way it is like we are married.', 565, 9),
    ]),
  ],
}

const johnMulaneyNewInTown: CuratedCollection = {
  id: 'john-mulaney-new-in-town',
  speakerId: 'john-mulaney',
  speaker: 'John Mulaney',
  sourceTitle: 'New in Town · Full Special',
  videoId: '5S5iZZEtTkg',
  videoTitle: 'John Mulaney: New in Town - Full Special',
  channelName: 'Comedy Central Stand-Up',
  thumbnail: 'https://i.ytimg.com/vi/5S5iZZEtTkg/hqdefault.jpg',
  duration: 2523,
  description: 'An official Comedy Central upload selected for sentence design, wording, pauses, act-outs, setup/payoff, and precise escalation. The clips favor complete joke units whose language can be shadowed without needing the whole special.',
  focus: ['Sentence design', 'Wording', 'Timing', 'Pauses', 'Act-outs', 'Setup and payoff'],
  status: 'ready',
  segments: [
    segmentWithLines('MUL-001', 124, 159, 'Specific detail · make a childhood fact absurd through one exact comparison', [
      transcriptLine('I was just talking to my mom the other week. I found out that when I was 10, Veronica was 13.', 124, 14),
      transcriptLine('So why was she in charge?', 138, 6),
      transcriptLine("That would be like if you're going out of town for the week and you paid a horse to watch your dog.", 145, 13),
      transcriptLine("People always shush animals. They've never spoken.", 158, 8),
    ]),
    segmentWithLines('MUL-002', 189, 235, 'Act-out · turn a movie title into a tightly escalating argument', [
      transcriptLine('I saw New York City in a movie when I was a kid. It was called Home Alone 2, Lost in New York.', 189, 18),
      transcriptLine('It is a sequel.', 207, 7),
      transcriptLine('Lost in New York? The streets are numbered. How did you get lost in New York?', 214, 15),
      transcriptLine("I wasn't a comedian back then, so I have to do it now.", 229, 12),
    ]),
    segmentWithLines('MUL-003', 2024, 2075, 'Setup and payoff · repeat a phrase until the premise changes shape', [
      transcriptLine('Sometimes I get nervous on airplanes, and the doctor just wrote him a Xanax prescription.', 2024, 19),
      transcriptLine("I look down and I see 'frequent urination,' and I was like, perfect, that'll be a super quick visit.", 2055, 20),
      transcriptLine("I'll just be like, 'Hey, sometimes I pee a lot,' and the doctor will be like, 'Me too. Crazy.'", 2068, 14),
    ]),
    segmentWithLines('MUL-004', 2085, 2145, 'Character voice · make a minor character memorable through a repeated physical bit', [
      transcriptLine('In the observation room there is a male nurse standing there, and he has a Batman sticker on his stethoscope.', 2085, 22),
      transcriptLine('A Batman necklace and a Batman watch. He was kind of moving around the whole time.', 2107, 18),
      transcriptLine("He was like, 'I am too blessed to be stressed. What are you allergic to besides work?'", 2125, 15),
    ]),
    segmentWithLines('MUL-005', 2367, 2438, 'Escalation · use a confident character voice, then break it with physical truth', [
      transcriptLine("I'm one of those people who, when you take blood from me, sometimes I can faint.", 2367, 18),
      transcriptLine("Batman said to me, 'You're not going to faint.'", 2387, 10),
      transcriptLine('I stick my arm out, Batman puts the needle in, and I immediately collapse on the ground.', 2399, 20),
      transcriptLine("The moral of the story is that if you've been nervous your entire life, you should ask your doctor about Xanax.", 2437, 22),
    ]),
  ],
}

const trevorLostSouthAfricanShow: CuratedCollection = {
  id: 'trevor-noah-lost-south-african-show',
  speakerId: 'trevor-noah',
  speaker: 'Trevor Noah',
  sourceTitle: 'The LOST South African Show · Full Special',
  videoId: 'fgH-0FuwshA',
  videoTitle: 'The LOST South African Show (2023) - FULL SPECIAL',
  channelName: 'Trevor Noah',
  thumbnail: 'https://i.ytimg.com/vi/fgH-0FuwshA/hqdefault.jpg',
  duration: 5855,
  description: 'Trevor Noah’s official full special, selected for audience connection, perspective shifts, warmth, and character voices. The clips stay with self-contained translation moves: a local experience, a new audience frame, and a clean turn.',
  focus: ['Audience connection', 'Perspective shifts', 'Warmth', 'Character voices', 'Translation', 'Callbacks'],
  status: 'ready',
  segments: [
    segmentWithLines('TRV-001', 53, 108, 'Audience connection · re-enter a room by naming the shared history', [
      transcriptLine('Ah, we made it everybody. We made it. Welcome to the show.', 53, 10),
      transcriptLine("We've been waiting for this. You've been waiting. I've been waiting.", 60, 13),
      transcriptLine('It could not happen because COVID was happening.', 66, 9),
      transcriptLine("They said the shows were limited. Then they said it's not limited, but now there's still COVID.", 71, 17),
      transcriptLine("I saw COVID in South Africa. I was like, uh-uh. I'm not going to take that chance.", 76, 13),
      transcriptLine("In America it was easy. They just asked you, 'Please don't go outside.' And if you did, they were like, 'Well, we tried.'", 80, 20),
    ]),
    segmentWithLines('TRV-002', 117, 173, 'Perspective shift · turn a small administrative detail into a homecoming story', [
      transcriptLine('Everyone asks me, Trevor, does it still feel like home?', 117, 11),
      transcriptLine('Guys, it will always feel like home. That does not change the people, the food, the culture.', 126, 18),
      transcriptLine('The reason it will always feel like home is because, even when I was in New York for eight years, I would get an SMS from the SABC telling me to pay my TV license.', 140, 20),
      transcriptLine('Those people are relentless. I was in New York. These people were still there.', 159, 14),
    ]),
    segmentWithLines('TRV-003', 173, 223, 'Character voices · build a second speaker with tiny, repeatable choices', [
      transcriptLine('They would come back with a second warning: pay your TV license.', 173, 13),
      transcriptLine('A few months later, I got referred to a debt collector.', 191, 10),
      transcriptLine('Literally, I was minding my own business, walking around in New York City, and my phone rings.', 203, 17),
      transcriptLine('Unknown numbers, unknown problems.', 215, 9),
    ]),
    segmentWithLines('TRV-004', 225, 292, 'Act-out · let a bureaucratic exchange escalate through voice and status', [
      transcriptLine("The voice was like, 'Hi, Mr. Noah. Am I speaking to Mr. Noah?'", 225, 12),
      transcriptLine("'I'm calling you from the vet and associates. We've been referred your case by the SABC.'", 233, 14),
      transcriptLine("'Your failure to pay means that we are now going to be attaching your assets.'", 241, 11),
      transcriptLine("I was like, 'Assets plural? That's 47 rand and 60.'", 250, 15),
      transcriptLine("They said, 'Actually, now it has gone up. It is now 49 rand because of interest.'", 259, 15),
      transcriptLine("I said, 'I don't live in South Africa, so I don't need a TV license.'", 267, 15),
    ]),
    segmentWithLines('TRV-005', 2005, 2071, 'Translation · explain a local reality by giving the outsider the wrong reaction first', [
      transcriptLine('One of the things I need to catch up to South Africans on is load shedding.', 2002, 13),
      transcriptLine("When I left South Africa, load shedding was like one hour every few weeks. Now they say it's stage six, and I'm like, is this Mario Brothers?", 2014, 23),
      transcriptLine('I still react to load shedding. South Africans do not flinch anymore.', 2038, 17),
      transcriptLine("When the lights go out, I'm the only idiot who's like, 'Ah, load shedding.'", 2050, 18),
      transcriptLine("People look at me like, 'Where's this guy from? He doesn't even know load shedding.'", 2057, 15),
    ]),
    segmentWithLines('TRV-006', 2072, 2134, 'Categorization · make a shared problem funny by giving it a ranking system', [
      transcriptLine("You've started becoming load-shedding connoisseurs.", 2072, 12),
      transcriptLine("People talk about their favorite load shedding: 'My favorite load is easily 2 a.m. to 6 a.m.'", 2083, 18),
      transcriptLine("That's when you want load, because you're already asleep. It doesn't bother anything.", 2099, 15),
      transcriptLine("You can't have a favorite bad thing. That's like someone saying, 'My favorite plane crash is the one that goes like this.'", 2115, 19),
    ]),
  ],
}

const hasanJflAdultBoy: CuratedCollection = {
  id: 'hasan-minhaj-adult-boy-jfl',
  speakerId: 'hasan-minhaj',
  speaker: 'Hasan Minhaj',
  sourceTitle: 'Adult Boy · JFL 2019 opening set',
  videoId: 'bufx3t2U_Oc',
  videoTitle: 'Hasan Minhaj and Guests | Adult Boy (JFL 2019)',
  channelName: '800 Pound Gorilla Media',
  thumbnail: 'https://i.ytimg.com/vi/bufx3t2U_Oc/hqdefault.jpg',
  duration: 2481,
  description: 'A long-form, stage-only JFL upload containing Hasan’s opening set before the guest performances begin. Only Hasan’s first six minutes are promoted, focusing on thesis, audience framing, personal stakes, escalation, and a clean visual idea.',
  focus: ['Thesis', 'Audience framing', 'Personal stakes', 'Escalation', 'Character voices', 'Presentation architecture'],
  status: 'ready',
  segments: [
    segmentWithLines('HAS-001', 43, 103, 'Personal stakes · establish the family story, then make the image specific', [
      transcriptLine('So many brown people showed up on time. I am flattered. I see you. We did it.', 43, 9),
      transcriptLine('My wife and I just had a daughter. We had a baby girl.', 50, 14),
      transcriptLine("I'll wake up in the morning and go to her crib. That's our time together.", 69, 14),
      transcriptLine("I'll look in the crib. She'll just be bundled up. She'll be staring at me. That's how I know she's Indian.", 72, 18),
      transcriptLine("'Hello, Daddy. I've been waiting for you.'", 87, 8),
    ]),
    segmentWithLines('HAS-002', 104, 141, 'Perspective shift · hold two identities in one sentence before the turn', [
      transcriptLine("She's Indian and Muslim, which is such an interesting combination.", 104, 13),
      transcriptLine('Think about it: to be something that people love. People love Indian culture.', 109, 16),
      transcriptLine('And then also be something that people hate.', 123, 9),
      transcriptLine('People hate Muslims. You know what I am talking about. Quebec.', 130, 11),
    ]),
    segmentWithLines('HAS-003', 180, 230, 'Language · turn a familiar phrase into a compact argument', [
      transcriptLine("My dad is worried. He'll call me Hassan and say, 'Don't talk about the Muslim stuff. Lean into the Indian.'", 180, 18),
      transcriptLine('Eleven straight spelling bees. People respect that.', 183, 12),
      transcriptLine('Indian, I mean, we are taking over: yoga, meditation, chai tea at Starbucks.', 190, 17),
      transcriptLine('Chai tea is the dumbest thing I have ever heard in my life. You are saying tea tea.', 205, 19),
      transcriptLine("It's like saying, 'Have you heard of this Mexican water? It's called aqua water.'", 217, 18),
    ]),
    segmentWithLines('HAS-004', 257, 322, 'Escalation · make the room see the contrast before you explain it', [
      transcriptLine('I want to be a good dad. I want to be a role model to her.', 257, 12),
      transcriptLine('I have lived in New York for six years, and that city turns you into a monster.', 264, 13),
      transcriptLine('Everyone in Manhattan is a sociopath.', 269, 7),
      transcriptLine('There was this beautiful woman in a flowing gown just puking in the bushes.', 280, 12),
      transcriptLine('Just the yin and yang of New York: beauty and horror all at once.', 293, 9),
      transcriptLine("Nobody is helping her. Everyone is walking by with white headphones, listening to a podcast about podcasts.", 297, 22),
    ]),
  ],
}

const georgeBackInTownStatePrisonFarms: CuratedCollection = {
  id: 'george-carlin-state-prison-farms',
  speakerId: 'george-carlin',
  speaker: 'George Carlin',
  sourceTitle: 'State Prison Farms · Back in Town',
  videoId: 'PkMrFIv_QHk',
  videoTitle: 'State Prison Farms | George Carlin | Back In Town (1996)',
  channelName: 'Official George Carlin',
  thumbnail: 'https://i.ytimg.com/vi/PkMrFIv_QHk/hqdefault.jpg',
  duration: 485,
  description: 'An official George Carlin performance clip selected for categorization, definition, contrast, verbal economy, and argument-building. The two clips preserve the move from premise to policy-shaped absurdity.',
  focus: ['Categorization', 'Contrast', 'Definitions', 'Verbal economy', 'Argument-building'],
  status: 'ready',
  segments: [
    segmentWithLines('CAR-001', 1, 34, 'Categorization · announce the system before naming the targets', [
      transcriptLine("I'm going to save you a whole lot of money on prisons, but at the same time, we are still going to remove from society many of our more annoying citizens.", 1, 17),
      transcriptLine('Four groups are going away permanently.', 9, 9),
      transcriptLine("First group, violent criminals. Here's what you do with these Emmy Award winners.", 12, 13),
      transcriptLine('You take the entire state of Kansas.', 21, 8),
    ]),
    segmentWithLines('CAR-002', 35, 74, 'Contrast · escalate a clean image until the argument lands as a joke', [
      transcriptLine('You put a big ten-story electric fence around Kansas.', 35, 11),
      transcriptLine('Kansas becomes a permanent prison farm for violent criminals.', 40, 12),
      transcriptLine('No parole, no police, no supplies.', 42, 10),
      transcriptLine('The only thing you give them is lethal weapons and live ammunition so they can communicate in a meaningful way.', 46, 19),
      transcriptLine('Then you put the whole thing on cable TV: the Violence Network, VNN.', 56, 15),
    ]),
  ],
}

const georgeCarlinRights: CuratedCollection = {
  id: 'george-carlin-you-have-no-rights',
  speakerId: 'george-carlin',
  speaker: 'George Carlin',
  sourceTitle: 'You Have No Rights · It\'s Bad for Ya',
  videoId: 'C_FQZUSy1Vg',
  videoTitle: "You Have No Rights | George Carlin | It's Bad for Ya (2008)",
  channelName: 'Official George Carlin',
  thumbnail: 'https://i.ytimg.com/vi/C_FQZUSy1Vg/hqdefault.jpg',
  duration: 297,
  description: 'An official performance selected for definitions, taxonomy, contrast, repetition, and intellectual clarity. The clips are deliberately short because Carlin’s useful units are often argument-shaped sentences rather than story arcs.',
  focus: ['Definitions', 'Categorization', 'Contrast', 'Word choice', 'Intellectual clarity', 'Verbal economy'],
  status: 'ready',
  segments: [
    segmentWithLines('CAR-003', 1, 63, 'Definition · reject a familiar category, then rebuild it precisely', [
      transcriptLine("Everyone in this country is always running around yammering about their rights.", 1, 11),
      transcriptLine("I hate to spoil your fun, but there's no such thing as rights. They're imaginary. We made them up.", 7, 22),
      transcriptLine("Rights are an idea. They're just imaginary. Cute idea, cute, but that's all.", 21, 16),
      transcriptLine('If you think you do have rights, let me ask you this: where do they come from?', 27, 12),
      transcriptLine('The God excuse: the last refuge of a man with no answers and no argument.', 37, 14),
    ]),
    segmentWithLines('CAR-004', 73, 151, 'Argument-building · use a list to expose a category error', [
      transcriptLine('Let us say God gave us these rights. Why would he give us a certain number of rights?', 73, 17),
      transcriptLine('The Bill of Rights in this country has ten stipulations.', 77, 13),
      transcriptLine('We have had to amend the Bill of Rights an additional seventeen times.', 83, 15),
      transcriptLine('God forgot a couple of things, like slavery. It just slipped his mind.', 90, 13),
      transcriptLine('That sounds more like human planning—one group trying to control another group.', 136, 15),
    ]),
    segmentWithLines('CAR-005', 151, 230, 'Historical contrast · repeat one phrase until its meaning changes', [
      transcriptLine('If you think you do have rights, one last assignment: go to Wikipedia and type in Japanese Americans 1942.', 151, 18),
      transcriptLine('In 1942 there were 110,000 Japanese American citizens in good standing who were thrown into internment camps.', 178, 18),
      transcriptLine('They had no right to a lawyer, no right to a fair trial, no right to a jury of their peers.', 191, 22),
      transcriptLine("Rights aren't rights if someone can take them away. They're privileges, that's all.", 210, 17),
      transcriptLine('Every year the list gets shorter and shorter and shorter.', 221, 13),
    ]),
    segmentWithLines('CAR-006', 237, 294, 'Strong ending · compress the thesis into a final reversal', [
      transcriptLine('Sooner or later, the people in this country are going to realize the government does not care about them.', 237, 18),
      transcriptLine("It's interested in its own power. That's the only thing keeping it and expanding it.", 248, 15),
      transcriptLine('When it comes to rights, I think either we have unlimited rights or we have no rights at all.', 254, 18),
      transcriptLine('Where are you going to find a fairer deal than that?', 273, 10),
      transcriptLine('Then shoot the guy and walk away.', 284, 9),
    ]),
  ],
}

const queuedStandUpSource = (
  speakerId: string,
  speaker: string,
  id: string,
  sourceTitle: string,
  videoId: string | null,
  videoTitle: string,
  channelName: string,
  duration: number,
  description: string,
  focus: string[],
  status: CuratedSourceStatus = 'queued',
): CuratedCollection => ({
  id,
  speakerId,
  speaker,
  sourceTitle,
  videoId,
  videoTitle,
  channelName,
  thumbnail: videoId ? `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg` : '',
  duration,
  description,
  focus,
  status,
  segments: [],
})

const queuedMikeSource = (
  id: string,
  sourceTitle: string,
  videoId: string,
  videoTitle: string,
  channelName: string,
  duration: number,
  description: string,
  status: CuratedSourceStatus = 'curating',
): CuratedCollection => ({
  id,
  speakerId: 'mike-birbiglia',
  speaker: 'Mike Birbiglia',
  sourceTitle,
  videoId,
  videoTitle,
  channelName,
  thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
  duration,
  description,
  focus: ['Storytelling', 'Performance', 'Transcript review'],
  status,
  segments: [],
})

const queuedSource = (
  id: string,
  sourceTitle: string,
  description: string,
  focus: string[],
): CuratedCollection => ({
  id,
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle,
  videoId: null,
  videoTitle: sourceTitle,
  channelName: '',
  thumbnail: '',
  duration: 0,
  description,
  focus,
  status: 'queued',
  segments: [],
})

export const CURATED_SPEAKERS: CuratedSpeaker[] = [
  {
    id: 'naval-ravikant',
    name: 'Naval Ravikant',
    description: 'Primary articulation study: turning complex thoughts into unusually clean language, with calm delivery, compression, precision, and conceptual structure.',
    focus: ['Articulation', 'Formulation', 'Clarity', 'Cadence', 'Compression', 'Thinking aloud'],
    portrait: 'https://i.ytimg.com/vi/KyfUysrNaco/hqdefault.jpg',
    sources: [
      navalJre,
      navalModernWisdom,
      navalKnowledgeProject18,
      navalTimFerriss473,
      navalHowToGetRich,
      navalSmartFriendsBuildingWealth,
      queuedSource('naval-smart-friends-philosophy', 'Smart Friends · Philosophy · 2025', 'Recent Naval on meaning, truth, authenticity, philosophy, risk, and end games.', ['Current style', 'Philosophy', 'Reflection']),
      queuedSource('naval-smart-friends-learning-happiness', 'Smart Friends · Learning Happiness · 2025', 'Recent Naval revisiting happiness, desire, learning, and self-observation.', ['Current style', 'Happiness', 'Learning']),
      queuedSource('naval-smart-friends-saving-yourself', 'Smart Friends · Saving Yourself · 2025', 'Recent Naval on authenticity, environment, iteration, envy, and self-direction.', ['Current style', 'Self-direction', 'Reflection']),
      queuedSource('naval-smart-friends-building-judgement', 'Smart Friends · Building Judgement · 2025', 'Recent Naval on judgment, decisions, knowledge, and long-term thinking.', ['Current style', 'Judgment', 'Decision-making']),
      navalTimFerriss97,
      navalAfterOnEndGames1,
      navalSellTheTruth,

      // Scientific / epistemology conversations — important for studying how Naval
      // asks, reframes, and explains around genuinely technical thinkers.
      queuedSource('naval-deutsch-knowledge-1', 'David Deutsch · Knowledge Creation and the Human Race · Part 1', 'Naval in sustained conversation with physicist David Deutsch on knowledge, AGI, explanations, and quantum computing.', ['Scientific dialogue', 'Questions', 'Clarification']),
      navalDeutschKnowledge2,
      navalDeutschFiles1,
      navalDeutschFiles2,
      queuedSource('naval-deutsch-files-3', 'The Deutsch Files III · 2024', 'Technical conversation around AGI, Popper, misunderstanding, and explanation.', ['Scientific dialogue', 'Disagreement', 'Precision']),
      queuedSource('naval-deutsch-files-4', 'The Deutsch Files IV · 2024', 'Long-form attempt to connect Deutsch’s major theories into one coherent picture.', ['Synthesis', 'Technical questioning', 'Conceptual structure']),
      queuedSource('naval-tim-ferriss-662', 'Tim Ferriss #662 · David Deutsch + Naval Ravikant', 'Naval alongside a leading physicist discussing reality, knowledge, AGI, quantum computing, optimism, and wealth.', ['Scientific dialogue', 'Translation', 'High-level synthesis']),
    ],
  },
  {
    id: 'mike-birbiglia',
    name: 'Mike Birbiglia',
    description: 'Storytelling and vulnerability: a performance study in clear story structure, personal detail, calm delivery, perspective shifts, callbacks, and emotional payoff.',
    focus: ['Storytelling', 'Vulnerability', 'Structure', 'Personal detail', 'Callbacks', 'Emotional payoff'],
    portrait: 'https://i.ytimg.com/vi/29LxAwlGTpk/hqdefault.jpg',
    sources: [
      mikeGirlfriendsBoyfriend,
      mikeWhatIShouldHaveSaid,
      mikeThirtyMinutesGirlfriendsBoyfriend,
      mikeThisAmericanLifeLive,
      queuedMikeSource(
        'mike-birbiglia-comedy-central-presents',
        'Comedy Central Presents · Full Special',
        '0q4xPU_OR6w',
        'Mike Birbiglia: Comedy Central Presents - Full Special',
        'Comedy Central Stand-Up',
        1272,
        'Performed half-hour candidate. It is currently unavailable in the curator\'s country, so it stays queued rather than being promoted.',
        'queued',
      ),
    ],
  },
  {
    id: 'john-mulaney',
    name: 'John Mulaney',
    description: 'Precision and rhythm: a sentence-level performance study in exact wording, pauses, act-outs, and setup/payoff.',
    focus: ['Precision', 'Rhythm', 'Wording', 'Timing', 'Act-outs', 'Payoff'],
    portrait: 'https://i.ytimg.com/vi/5S5iZZEtTkg/hqdefault.jpg',
    sources: [
      johnMulaneyNewInTown,
      queuedStandUpSource(
        'john-mulaney',
        'John Mulaney',
        'john-mulaney-comeback-kid',
        'The Comeback Kid · full-special candidate',
        null,
        'John Mulaney: The Comeback Kid',
        'Netflix',
        0,
        'A second performed special candidate. It stays queued until a playable source and reliable caption timebase are available.',
        ['Precision', 'Rhythm', 'Transcript review'],
      ),
    ],
  },
  {
    id: 'trevor-noah',
    name: 'Trevor Noah',
    description: 'Audience connection and translation: making a local experience legible to a new audience through warmth, perspective shifts, and character voices.',
    focus: ['Audience connection', 'Translation', 'Warmth', 'Perspective shifts', 'Character voices'],
    portrait: 'https://i.ytimg.com/vi/fgH-0FuwshA/hqdefault.jpg',
    sources: [
      trevorLostSouthAfricanShow,
      queuedStandUpSource(
        'trevor-noah',
        'Trevor Noah',
        'trevor-noah-pay-back-the-funny',
        'Pay Back The Funny · full-show candidate',
        '1dOPpoUDdkw',
        'Trevor Noah - Pay Back The Funny (Full Stand Up 2015)',
        'Zolani Hogana',
        5063,
        'A full-show candidate with unverified channel provenance. It stays queued until the source and playback rights are reviewed.',
        ['Translation', 'Audience connection', 'Character voices'],
      ),
    ],
  },
  {
    id: 'hasan-minhaj',
    name: 'Hasan Minhaj',
    description: 'Presentation architecture: building a thesis through evidence, visuals, escalation, personal stakes, and dramatic structure.',
    focus: ['Architecture', 'Thesis', 'Evidence', 'Escalation', 'Personal stakes', 'Visual logic'],
    portrait: 'https://i.ytimg.com/vi/bufx3t2U_Oc/hqdefault.jpg',
    sources: [
      hasanJflAdultBoy,
      queuedStandUpSource(
        'hasan-minhaj',
        'Hasan Minhaj',
        'hasan-minhaj-homecoming-king',
        'Homecoming King · full-special candidate',
        null,
        'Hasan Minhaj: Homecoming King',
        'Netflix',
        0,
        'The complete special is a Netflix release, not a verified playable YouTube source. Keep it queued until a usable source with a dependable timebase is available.',
        ['Presentation architecture', 'Thesis', 'Personal stakes'],
      ),
    ],
  },
  {
    id: 'chris-rock',
    name: 'Chris Rock',
    description: 'Persuasive force: using repetition, emphasis, rhythm, vocal energy, and strong opinions to build an argument people can feel.',
    focus: ['Persuasion', 'Repetition', 'Emphasis', 'Rhythm', 'Vocal energy', 'Arguments'],
    portrait: 'https://i.ytimg.com/vi/coC4t7nCGPs/hqdefault.jpg',
    sources: [
      queuedStandUpSource(
        'chris-rock',
        'Chris Rock',
        'chris-rock-bring-the-pain',
        'Bring the Pain · full-show candidate',
        'coC4t7nCGPs',
        'Chris Rock - Bring The Pain (1996) FULL SHOW [Stand Up Comedy]',
        'Art Of Sports',
        3499,
        'A performed full-show candidate, but the channel provenance and rights are not verified. It stays out of practice until that is resolved.',
        ['Repetition', 'Emphasis', 'Rhythm', 'Vocal energy', 'Argument-building'],
      ),
    ],
  },
  {
    id: 'george-carlin',
    name: 'George Carlin',
    description: 'Language and thinking: sharpening an idea through definitions, categories, contrast, word choice, and verbal economy.',
    focus: ['Definitions', 'Categories', 'Contrast', 'Word choice', 'Clarity', 'Economy'],
    portrait: 'https://i.ytimg.com/vi/C_FQZUSy1Vg/hqdefault.jpg',
    sources: [
      georgeBackInTownStatePrisonFarms,
      georgeCarlinRights,
      queuedStandUpSource(
        'george-carlin',
        'George Carlin',
        'george-carlin-back-in-town-full-show',
        'Back in Town · full-show candidate',
        'MK2W2cyAzLI',
        'The legend George Carlin 1996 full show - Back in town 👌',
        'Mat Stone',
        3766,
        'A full-show candidate with unverified channel provenance. It stays queued until the source and playback rights are reviewed.',
        ['Language', 'Definitions', 'Contrast', 'Verbal economy'],
      ),
    ],
  },
]

export const CURATED_COLLECTIONS: CuratedCollection[] = CURATED_SPEAKERS.flatMap(speaker =>
  speaker.sources.filter(source => source.status === 'ready'),
)

export function getCuratedSpeaker(id: string | null | undefined): CuratedSpeaker | null {
  if (!id) return null
  return CURATED_SPEAKERS.find(speaker => speaker.id === id) || null
}

export function getCuratedCollection(id: string | null | undefined): CuratedCollection | null {
  if (!id) return null
  return CURATED_COLLECTIONS.find(collection => collection.id === id) || null
}
