import type { CuratedCollection } from './curated-library'
import type { Segment } from './types'

const segment = (id: string, start: number, end: number, label: string): Segment => ({
  id, start, end, label, lines: [], createdAt: 0,
})

export const navalSmartFriendsPhilosophy: CuratedCollection = {
  id: 'naval-smart-friends-philosophy',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Smart Friends · Philosophy · 2025',
  videoId: 'buHeUV_tXtc',
  videoTitle: 'My Conversation with Naval on Philosophy',
  channelName: 'Eric Jorgenson',
  thumbnail: 'https://i.ytimg.com/vi/buHeUV_tXtc/hqdefault.jpg',
  duration: 2719,
  description: 'Recent Naval on truth, authenticity, philosophy, meaning, learning, retirement, and end games. Selected for reflective formulation, analogies, distinctions, and clean conceptual structure.',
  focus: ['Current style', 'Philosophy', 'Reflection', 'Formulation', 'Analogy'],
  status: 'ready',
  segments: [
    segment('SF-PHIL-001', 117.76, 138.38, 'Values · God, family, and a mission larger than yourself'),
    segment('SF-PHIL-002', 177.22, 212.98, 'Distinction · introspection versus rumination'),
    segment('SF-PHIL-003', 327.02, 371.82, 'Explanation · group cohesion can compete with truth'),
    segment('SF-PHIL-004', 507.64, 544.94, 'Framework · spreadable truth, lies, and hidden heresies'),
    segment('SF-PHIL-005', 561.12, 596.52, 'Reframing · look for non-consensus truths'),
    segment('SF-PHIL-006', 902.78, 942.88, 'Analogy · the Matrix white room and pure awareness'),
    segment('SF-PHIL-007', 1077.60, 1105.54, 'Reframing · simulation theory as a high-agency frame'),
    segment('SF-PHIL-008', 1121.66, 1145.44, 'Analogy · each era projects its worldview onto religion'),
    segment('SF-PHIL-009', 1302.72, 1330.88, 'Principle · live on your own terms and for something larger'),
    segment('SF-PHIL-010', 1456.40, 1477.02, 'Decision rule · read timeless ideas or the moving frontier'),
    segment('SF-PHIL-011', 1598.88, 1628.14, 'Explanation · elusive goals are often best pursued indirectly'),
    segment('SF-PHIL-012', 1830.34, 1859.00, 'Learning · use fun as a criterion for genuine curiosity'),
    segment('SF-PHIL-013', 2163.08, 2204.19, 'Synthesis · retirement, truth, love, health, and a calm mind'),
    segment('SF-PHIL-014', 2434.77, 2457.29, 'Analogy · life as end-game content with less fear'),
  ],
}

export const navalSmartFriendsLearningHappiness: CuratedCollection = {
  id: 'naval-smart-friends-learning-happiness',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Smart Friends · Learning Happiness · 2025',
  videoId: '0HiUWufjzuM',
  videoTitle: 'My Conversation with Naval on Learning Happiness',
  channelName: 'Eric Jorgenson',
  thumbnail: 'https://i.ytimg.com/vi/0HiUWufjzuM/hqdefault.jpg',
  duration: 3816,
  description: 'Recent Naval revisiting happiness, desire, identity, meditation, relationships, and self-observation. Selected for concise reframing, self-correction, and reflective explanation.',
  focus: ['Current style', 'Happiness', 'Learning', 'Self-observation', 'Reframing'],
  status: 'ready',
  segments: [
    segment('SF-HAPPY-001', 285.70, 328.98, 'Self-correction · prefer being okay with reality over chasing happiness'),
    segment('SF-HAPPY-002', 358.24, 371.90, 'Compression · the more you think about yourself, the less happy you are'),
    segment('SF-HAPPY-003', 417.46, 456.32, 'Decision rule · strategic indifference to what you cannot control'),
    segment('SF-HAPPY-004', 544.08, 563.62, 'Reframing · do what you do without overthinking why'),
    segment('SF-HAPPY-005', 907.64, 932.44, 'Formulation · truth quiets the mind'),
    segment('SF-HAPPY-006', 1122.36, 1144.88, 'Distinction · being in love versus being loved'),
    segment('SF-HAPPY-007', 1300.41, 1327.49, 'Definition · chronic unhappiness can become an identity'),
    segment('SF-HAPPY-008', 1351.87, 1366.21, 'Formulation · keep identity thin'),
    segment('SF-HAPPY-009', 1543.35, 1579.97, 'Explanation · ideas can change a mind faster than techniques'),
    segment('SF-HAPPY-010', 1841.81, 1861.53, 'Ordering · wealth, health, and happiness across life'),
    segment('SF-HAPPY-011', 2018.51, 2044.85, 'Explanation · design a life with fewer unwanted obligations'),
    segment('SF-HAPPY-012', 2234.85, 2248.29, 'Meditation · thoughts are events, not the self'),
    segment('SF-HAPPY-013', 3498.21, 3527.15, 'Relationship rule · two happy people work on themselves'),
    segment('SF-HAPPY-014', 3680.11, 3704.07, 'Distinction · ritualized positivity versus genuine gratitude'),
  ],
}

export const navalSmartFriendsSavingYourself: CuratedCollection = {
  id: 'naval-smart-friends-saving-yourself',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Smart Friends · Saving Yourself · 2025',
  videoId: 'vt8wd-i4n0I',
  videoTitle: 'My Conversation with Naval on Saving Yourself',
  channelName: 'Eric Jorgenson',
  thumbnail: 'https://i.ytimg.com/vi/vt8wd-i4n0I/hqdefault.jpg',
  duration: 2149,
  description: 'Recent Naval on virtues, authenticity, environment, iteration, envy, compounding, and self-direction. Selected for practical rules, clean reframes, and memorable explanatory language.',
  focus: ['Current style', 'Self-direction', 'Authenticity', 'Judgment', 'Reframing'],
  status: 'ready',
  segments: [
    segment('SF-SAVE-001', 44.86, 74.12, 'Reframing · virtues as long-term self-interest'),
    segment('SF-SAVE-002', 81.96, 108.20, 'Definition · virtues create individual and collective wins'),
    segment('SF-SAVE-003', 189.62, 228.20, 'Decision rule · solve local problems before claiming global answers'),
    segment('SF-SAVE-004', 284.68, 307.84, 'Leadership · a mission larger than yourself rallies people'),
    segment('SF-SAVE-005', 367.36, 389.28, 'Distinction · ideas spread by spreadability and survive by correctness'),
    segment('SF-SAVE-006', 728.70, 761.70, 'Definition · authenticity means dropping the projected mask'),
    segment('SF-SAVE-007', 1253.63, 1297.63, 'Compounding · find work, people, and places you can invest in'),
    segment('SF-SAVE-008', 1415.85, 1448.25, 'Learning · iteration develops judgment'),
    segment('SF-SAVE-009', 1623.29, 1651.49, 'Environment · choose where you can become your best self'),
    segment('SF-SAVE-010', 1786.33, 1826.53, 'Reframing · turn envy into inspiration'),
    segment('SF-SAVE-011', 1980.51, 2023.75, 'Storytelling · borrow permission from people who resonate with you'),
    segment('SF-SAVE-012', 2125.77, 2147.11, 'Decision rule · want the long-term things first'),
  ],
}

export const navalSmartFriendsBuildingJudgement: CuratedCollection = {
  id: 'naval-smart-friends-building-judgement',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Smart Friends · Building Judgement · 2025',
  videoId: '3lzfXM0qcuU',
  videoTitle: 'My Conversation with Naval on Building Judgement',
  channelName: 'Eric Jorgenson',
  thumbnail: 'https://i.ytimg.com/vi/3lzfXM0qcuU/hqdefault.jpg',
  duration: 2128,
  description: 'Recent Naval on judgment, timeless versus timely knowledge, taste, hard work, AI, and decision-making. Selected for first-principles explanation and reusable reasoning structures.',
  focus: ['Current style', 'Judgment', 'Decision-making', 'Explanation', 'Taste'],
  status: 'ready',
  segments: [
    segment('SF-JUDGE-001', 43.06, 81.10, 'Framing · humans search for something perfect and permanent'),
    segment('SF-JUDGE-002', 81.10, 124.82, 'Distinction · study the fast-moving frontier and timeless human nature'),
    segment('SF-JUDGE-003', 125.26, 167.06, 'Decision rule · modern knowledge should be useful, not gossip'),
    segment('SF-JUDGE-004', 248.10, 289.12, 'Explanation · good theories have reach'),
    segment('SF-JUDGE-005', 358.28, 392.30, 'Reasoning · truth implies something wider than place and time'),
    segment('SF-JUDGE-006', 529.46, 561.00, 'Experience · practical know-how compresses into principles'),
    segment('SF-JUDGE-007', 582.36, 621.84, 'Qualification · heuristics have contexts, not universal proofs'),
    segment('SF-JUDGE-008', 894.50, 930.80, 'Synthesis · experience becomes knowledge, values, and judgment'),
    segment('SF-JUDGE-009', 1096.12, 1139.44, 'Taste · understand what you genuinely care to work on'),
    segment('SF-JUDGE-010', 1257.50, 1268.22, 'Compression · intense work accelerates breakthroughs'),
    segment('SF-JUDGE-011', 1428.60, 1452.58, 'Qualification · hard work matters, forced work loses'),
    segment('SF-JUDGE-012', 1465.50, 1486.48, 'Learning · explicit reasoning gradually becomes implicit taste'),
    segment('SF-JUDGE-013', 1617.98, 1657.42, 'Distinction · AI retrieves information; humans bring values and judgment'),
    segment('SF-JUDGE-014', 1993.50, 2025.38, 'Reframing · AI removes drudgery, but novelty still needs understanding'),
  ],
}

export const navalDeutschKnowledge1: CuratedCollection = {
  id: 'naval-deutsch-knowledge-1',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'David Deutsch · Knowledge Creation and the Human Race · Part 1',
  videoId: 'YyxepLfH1ZU',
  videoTitle: 'David Deutsch: Knowledge Creation and The Human Race, Part 1',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/YyxepLfH1ZU/hqdefault.jpg',
  duration: 2631,
  description: 'Naval in sustained conversation with David Deutsch on knowledge, explanations, optimism, resources, AGI, and error correction. Selected for technical translation and question framing.',
  focus: ['Scientific dialogue', 'Questions', 'Clarification', 'Explanation', 'Synthesis'],
  status: 'ready',
  segments: [
    segment('DD-K1-001', 0.18, 17.68, 'Opening · define the purpose of a difficult conversation'),
    segment('DD-K1-002', 18.12, 42.14, 'Recommendation · explain why dense books repay rereading'),
    segment('DD-K1-003', 94.44, 131.54, 'Synthesis · four theories form one worldview'),
    segment('DD-K1-004', 325.76, 366.30, 'Definition · knowledge survives, replicates, and changes the universe'),
    segment('DD-K1-005', 638.26, 682.78, 'Reframing · people are knowledge creators, not just resource consumers'),
    segment('DD-K1-006', 754.92, 791.36, 'Definition · wealth expands through knowledge'),
    segment('DD-K1-007', 911.08, 942.98, 'Warning · protect error correction or societies stagnate'),
    segment('DD-K1-008', 1668.78, 1684.64, 'Question framing · ask for a usable definition of a good explanation'),
  ],
}

export const navalDeutschFiles3: CuratedCollection = {
  id: 'naval-deutsch-files-3',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'The Deutsch Files III · 2024',
  videoId: 'fizPWAAo-lc',
  videoTitle: 'The Deutsch Files III',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/fizPWAAo-lc/hqdefault.jpg',
  duration: 3559,
  description: 'Technical conversation with David Deutsch and Brett Hall. Naval’s strongest turns here are question framing, conceptual clarification, personal examples, and skepticism about group dogma.',
  focus: ['Scientific dialogue', 'Question framing', 'Precision', 'Creativity', 'Individual thinking'],
  status: 'ready',
  segments: [
    segment('DD-F3-001', 181.36, 224.90, 'Question framing · creativity, free will, and what creativity is not'),
    segment('DD-F3-002', 1611.96, 1628.50, 'Clarification · unschooling versus homeschooling'),
    segment('DD-F3-003', 2872.08, 2895.84, 'Storytelling · childhood curiosity and reading'),
    segment('DD-F3-004', 2903.44, 2926.14, 'Question framing · ask for conjectures beyond current evidence'),
    segment('DD-F3-005', 3180.62, 3221.56, 'Question framing · existence and consciousness as a central mystery'),
    segment('DD-F3-006', 3515.74, 3549.34, 'Principle · free thinking comes from individuals, not named groups'),
  ],
}

export const navalDeutschFiles4: CuratedCollection = {
  id: 'naval-deutsch-files-4',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'The Deutsch Files IV · 2024',
  videoId: 'WUEUozkGXes',
  videoTitle: 'The Deutsch Files IV',
  channelName: 'Naval',
  thumbnail: 'https://i.ytimg.com/vi/WUEUozkGXes/hqdefault.jpg',
  duration: 5106,
  description: 'Long-form attempt to connect Deutsch’s major theories into one coherent picture. Selected for synthesis, technical questioning, institutional reasoning, and conceptual compression.',
  focus: ['Synthesis', 'Technical questioning', 'Conceptual structure', 'Institutions', 'Education'],
  status: 'ready',
  segments: [
    segment('DD-F4-001', 0.00, 35.02, 'Synthesis · connect the four strands instead of treating them separately'),
    segment('DD-F4-002', 612.62, 642.20, 'Question framing · what problem is constructor theory solving?'),
    segment('DD-F4-003', 1366.56, 1410.00, 'Technical questioning · connect many-worlds to quantum computation'),
    segment('DD-F4-004', 1872.06, 1909.72, 'Clarification · define anti-rational memes'),
    segment('DD-F4-005', 2550.58, 2578.04, 'Institutions · load-bearing systems can be hijacked under old brands'),
    segment('DD-F4-006', 2632.18, 2658.42, 'Reasoning · rapid change can produce pressure for restrictive regulation'),
    segment('DD-F4-007', 3090.88, 3119.90, 'Reframing · alternative media reveals control; then question education'),
    segment('DD-F4-008', 3298.92, 3316.46, 'Question framing · a parent’s fear about unschooling'),
  ],
}

export const navalTimFerriss662: CuratedCollection = {
  id: 'naval-tim-ferriss-662',
  speakerId: 'naval-ravikant',
  speaker: 'Naval Ravikant',
  sourceTitle: 'Tim Ferriss #662 · David Deutsch + Naval Ravikant',
  videoId: 'FfWbcrObpUY',
  videoTitle: 'David Deutsch and Naval Ravikant — The Fabric of Reality',
  channelName: 'Tim Ferriss',
  thumbnail: 'https://i.ytimg.com/vi/FfWbcrObpUY/hqdefault.jpg',
  duration: 6500,
  description: 'Naval alongside David Deutsch and Tim Ferriss on reality, knowledge, AGI, optimism, and wealth. Selected for translation, synthesis, technical questioning, and unusually clear conceptual framing.',
  focus: ['Scientific dialogue', 'Translation', 'High-level synthesis', 'Questions', 'Explanation'],
  status: 'ready',
  segments: [
    segment('TF662-001', 514.36, 547.08, 'Recommendation · explain why two books changed your worldview'),
    segment('TF662-002', 547.08, 582.34, 'Synthesis · compress a large worldview into its consequences'),
    segment('TF662-003', 2185.76, 2198.58, 'Synthesis · nature has no boundaries between disciplines'),
    segment('TF662-004', 2260.75, 2275.95, 'Question framing · ask for the hallmark of a good explanation'),
    segment('TF662-005', 3383.01, 3414.49, 'Clarification · creativity separates AGI from narrow AI'),
    segment('TF662-006', 4985.39, 5021.49, 'Definition · wealth as transformations enabled by knowledge'),
    segment('TF662-007', 5872.35, 5913.15, 'Question framing · error correction as a moral imperative'),
    segment('TF662-008', 5978.19, 6017.29, 'Strong ending · read for understanding, not completion'),
  ],
}
