import type { CuratedCollection, CuratedSpeaker } from './curated-library'
import type { Segment } from './types'

type Spec = [string, string, string, number, 'S'|'A', Array<[number, number, string]>]
const SPECS: Spec[] = [
  ['essence-calculus','WUvTyaaNkzM','The essence of calculus',1025,'S',[[36,57,'Goal · replace memorization with the feeling of invention'], [57,86,'Pedagogical standard · why is weaker than rediscovery'], [86,119,'Question construction · one concrete puzzle opens three abstract ideas'], [399,433,'Generalization · after the answer, extract the reusable method'], [564,595,'Reframing · many sums become areas when represented differently'], [673,694,'Problem solving · play with the question before attacking it directly'], [920,950,'Landing · derivatives and integrals click as inverse viewpoints']]],
  ['matrix-multiplication','XkY2DOUCWMU','Matrix multiplication as composition | Chapter 4, Essence of linear algebra',604,'S',[[93,118,'Representation · matrix as transformation, not a grid of numbers'], [222,245,'Reorientation · return from symbols to geometric meaning'], [356,374,'Motivation · explain why a more general rule is needed before stating it'], [420,447,'Concept before memorization · composition makes the rule inevitable'], [447,471,'Question construction · does order matter?'], [498,524,'Mental model · associativity becomes obvious through composition'], [524,552,'Explanation · geometry does more work than symbolic proof'], [552,582,'Practice · play with the representation until the rule feels natural']]],
  ['span-basis','k7RM-ot2NWY','Linear combinations, span, and basis vectors | Chapter 2, Essence of linear algebra',599,'S',[[23,62,'Reframing · coordinates become actions on basis vectors'], [80,107,'Delayed definition · build intuitive basis before technical language'], [191,223,'Terminology · make the word linear visible before naming the concept'], [267,297,'Compression · span means everything the allowed moves can reach'], [283,327,'Representation switch · arrows become points when the picture gets crowded'], [385,414,'Mental model · two independent knobs sweep out a sheet'], [444,475,'Contrast · redundancy versus opening a genuinely new direction'], [546,562,'Definition · technical language arrives only after the picture is stable']]],
  ['vectors','fNk_zzaMoSs','Vectors | Chapter 1, Essence of linear algebra',592,'S',[[10,51,'Contrast · three communities mean different things by vector'], [85,118,'Pedagogical order · postpone abstraction until concrete intuition exists'], [118,139,'Mental model · start with the arrow'], [139,161,'Translation · move from geometric arrow to coordinate pair'], [312,345,'Motivation · vector addition as movement, not a formula'], [345,362,'Analogy · addition should extend the operation you already know'], [362,386,'Translation · geometric movement becomes coordinate arithmetic'], [509,552,'Synthesis · the power comes from moving fluently between geometry and numbers']]],
  ['neural-network','aircAruvnKk','But what is a neural network? | Deep learning chapter 1',1120,'S',[[4,28,'Hook · begin from an effortless human capability'], [28,67,'Contrast · effortless perception versus daunting explicit programming'], [67,85,'Scope · promise the mathematics, not the buzzword'], [85,109,'Motivation · make the architecture feel necessary rather than arbitrary'], [149,168,'Question construction · break the name into the question the learner needs'], [168,194,'Simplification · a neuron begins as nothing more than a number holder'], [226,254,'Architecture · expose input and output while leaving the middle as the mystery'], [254,273,'Qualification · separate pedagogical choices from mathematical necessity'], [273,298,'Transition · identify the heart of the mechanism before adding machinery'], [917,939,'Reframing · a neuron can be understood as a function']]],
  ['backprop-intuition','Ilg3gGewQ5U','Backpropagation, intuitively | Deep Learning Chapter 3',767,'S',[[4,23,'Promise · intuition before formulas'], [168,215,'Confusion repair · name the notation-and-indexing failure mode'], [635,656,'Recap · compress the algorithm back into a causal picture'], [687,730,'Qualification · separate the mathematical mechanism from the representation of data']]],
  ['backprop-calculus','tIeHLnjs5U8','Backpropagation calculus | Deep Learning Chapter 4',618,'S',[[4,39,'Framing · formalize an intuition rather than starting over'], [121,161,'Simplification · replace symbol overload with a causal chain'], [161,191,'Translation · notation becomes a sequence of physical nudges'], [191,236,'Reframing · chain rule as propagated influence'], [285,309,'Zoom out · return from formulas to what the quantities mean'], [386,419,'Generalization · toy example first, complexity later'], [508,539,'Complication · add multiple causal paths only after the simple case is stable'], [553,574,'Recap · compress backpropagation into chain-rule sensitivities'], [574,617,'Metacognition · difficult notation needs digestion, not faster explanation']]],
  ['convolution','KuXjwB4LzSA','But what is a convolution?',1381,'S',[[60,99,'Meta-teaching · the formula is intimidating in isolation, so motivate the operation first'], [118,165,'Example choice · probability gives the most representative first picture'], [165,212,'Question construction · ask the learner for another way to visualize the same operation'], [286,327,'Delayed definition · formalism arrives after the example has earned it'], [327,365,'Multiple models · keep two mental pictures; notation is secondary'], [653,696,'Prediction · pause before the edge-detector example and make the learner guess'], [696,736,'Inference · reason from the picture instead of memorizing an effect'], [1266,1314,'Synthesis · one concept unifies probability, image processing, and other domains']]],
  ['two-problem-solvers','ltLUadnCyi0','A tale of two problem solvers | Average cube shadow area',2406,'S',[[0,15,'Meta-goal · the real lesson is problem-solving style, not the puzzle'], [15,35,'Characterization · personify the calculation-first mindset'], [35,73,'Contrast · structure-first thinking sees a different problem'], [206,223,'Operationalize · turn a vague average into an experiment'], [269,289,'Delayed formalism · make the question concrete before defining the integral'], [289,307,'Meta-goal · restate what the learner should be watching for'], [307,325,'Participation · invite the learner to pause and own the next idea'], [325,344,'Simplification · hard problem → simplest nontrivial variant'], [716,736,'Question construction · which properties of the cube actually matter?'], [1683,1702,'Contrast payoff · let one method\'s pain make the elegant method visible']]],
  ['moser-circle','YtkIWDE36qU','This pattern breaks, but for a good reason | Moser\'s circle problem',973,'A',[[0,20,'Hook · state the famous trap and promise the deeper reason'], [48,68,'Prediction · force commitment before revealing the next case'], [112,131,'Architecture · promise both a solution and a transferable problem-solving lesson'], [159,182,'Method · if stuck, solve an easier related question'], [245,271,'Dead end · show the tempting route, then invite a pause'], [402,427,'Leverage · introduce a theorem because the learner now needs it'], [463,485,'Invariant · build the theorem from a trivial case'], [671,691,'Curiosity · the numerical answer is not enough; explain why the pattern broke']]],
  ['pi-normal','cy8r7WSuT1I','Why π is in the normal distribution (beyond integral tricks)',1486,'A',[[40,59,'Question construction · an anecdote produces the real mathematical question'], [98,116,'Standard · go beyond proving the fact; explain why it should be true'], [116,137,'Success criterion · demand a full conceptual bridge, not a trick'], [179,195,'Meta-teaching · the first successful step is not yet the explanation'], [195,224,'Reframing · restate the goal at a deeper level'], [315,332,'Method · when the routine approach stalls, add a dimension'], [332,349,'Qualification · admit the move is unmotivated and search nearby problems'], [385,414,'Method choice · let symmetry tell you which representation to use']]],
  ['quantum-computing','RQWpF2Gb-gU','But what is quantum computing? (Grover\'s Algorithm)',2214,'A',[[0,22,'Misconception · start from the popular story'], [22,57,'Diagnostic · do not merely correct it; make the viewer test the belief'], [57,77,'Warm-up · reduce the mystery to a tiny function problem']]],
  ['topology-open-problem','IQqtsm-bBRU','This open problem taught me what topology is',1646,'S',[[46,69,'Motivation · abstract mathematics appears as a problem-solving tool'], [96,118,'Transfer · defend the puzzle by the habits of thought it teaches'], [118,137,'Personal motivation · topology became meaningful through use'], [155,173,'Reframing · reject the usual rubber-sheet introduction'], [173,194,'Method · abstraction as a tool for deduction, not decoration'], [194,226,'Representation · four vertices become two equal segments'], [226,249,'Participation · invite the proof pause before continuing'], [561,585,'Architecture · plant a representation early because it will matter later'], [762,787,'Emergence · topology arrives naturally from the representation'], [954,978,'Emergence · the Möbius strip is discovered rather than imposed']]],
  ['attention-transformers','eMlx5fFNoYc','Attention in transformers, step-by-step | Deep Learning Chapter 6',1570,'S',[[26,57,'Simplification · deliberately simplify tokenization so the rest stays thinkable'], [88,109,'Reassurance · normalize confusion before adding machinery'], [322,344,'Goal setting · name the local problem before introducing matrices'], [467,492,'Operational definition · keys are explained through the questions they answer'], [492,514,'Mechanism · alignment naturally suggests a dot product'], [514,546,'Visualization · turn pairwise relevance into a visible grid'], [790,815,'Transition · after relevance, ask what information should actually move'], [1296,1323,'Recap · compress the mechanism and reassure the learner before going deeper']]],
  ['transformers','wjZofJX0v4M','Transformers, the tech behind LLMs | Deep Learning Chapter 5',1634,'S',[[0,43,'Framing · decode the name, isolate the mystery, promise a data-flow walkthrough'], [432,459,'Prerequisite reset · re-establish the neural-network picture without derailing'], [459,499,'Contrast · machine learning versus explicit programming'], [562,581,'Constraints first · architecture should feel shaped by the problem'], [747,775,'Simplification · acknowledge the gap between human words and model tokens']]],
  ['reinventing-entropy','l6DKRf-fAAM','Reinventing Entropy | Compression is Intelligence Part 1',1939,'S',[[0,32,'Question hook · begin from a fundamental limit'], [32,59,'Method shift · make rediscovery, not the answer, the point'], [59,83,'Bridge · connect modern AI to old information theory'], [83,106,'Reframing · prediction becomes compression'], [106,134,'Qualification · temper the seductive claim without killing curiosity'], [134,156,'Learning goal · rediscover the theorem rather than receive it'], [156,178,'Meta-teaching · definitions are residue of insight'], [178,199,'Delayed formalism · preserve the story before showing the formula'], [403,425,'Anticipation · turn the learner\'s objection into the next question'], [839,887,'Insight → definition · let the optimization picture force the formal quantity'], [887,907,'Compression · decode the ugly expression as a spatial action'], [1469,1505,'Metacognition · rediscovery makes formulas memorable and grounded']]],
  ['cross-entropy','GlYgs6v2YfU','But what is cross-entropy? | Compression is Intelligence Part 2',2031,'S',[[881,925,'Bridge · connect compression directly to the LLM training objective'], [1238,1286,'Why-question · reject the shallow \'because it is the loss\' explanation'], [1470,1511,'Forest before trees · keep the derivation high level before algebra'], [1967,1999,'Ending · leave three questions that let the learner test real understanding']]],
  ['laplace-transform','j0wJBEZdwLs','But what is a Laplace Transform?',2081,'S',[[18,39,'Analogy · using a tool versus understanding its engine'], [39,60,'Goal · pop the hood before teaching procedures'], [60,77,'Memory · understanding makes formulas easier to retain'], [77,101,'Delayed definition · motivate the problem before naming the transform'], [380,429,'Preview · show the transformed behavior before formal definition']]],
  ['laplace-useful','FE-hM1kRK4Y','Why Laplace transforms are so useful',1385,'A',[[1074,1093,'Plural explanation · offer multiple views with different trade-offs'], [1093,1116,'Sanity check · test the new formula on a familiar example'], [1181,1201,'Toy case · a simple example contains the seeds of the general rule'], [1225,1249,'Warning · textbook derivation can be correct while intuition evaporates']]],
  ['euler-laplace-prelude','-j8PzkZ70Lg','The Physics of Euler\'s Formula | Laplace Transform Prelude',1669,'A',[[0,21,'Framework · build the mental machinery before the formal tool'], [21,44,'Meta-teaching · justify why the prelude deserves its own lesson'], [44,67,'Motivation · let a physical system make complex exponentials necessary']]],
  ['hairy-ball','BHdbsHFs2P0','Why you can\'t comb a hairy ball, and why we care',1780,'A',[[0,25,'Hook · a cowlick makes the theorem physically intuitive'], [25,49,'Play · test the claim mentally before formalizing it'], [231,275,'Abstraction · a grooming question becomes a tangent-vector-field question'], [878,904,'Meta-teaching · explain why proof by contradiction is intrinsically hard to animate']]],
  ['beautiful-formula','fsLh-NYhOoU','The most beautiful formula not enough people understand',3624,'A',[[5,27,'Motivation · ask where the formula comes from, not merely what it states'], [27,56,'Architecture · lead with puzzles because the formula is too abstract on its own']]],
  ['log-image','ldxFjLJ3rVY','How (and why) to take a logarithm of an image',2692,'S',[[0,27,'Meta-story · an animation problem is what made the mathematics click'], [27,53,'Context · start in the art room rather than the math classroom']]],
]

const sources: CuratedCollection[] = SPECS.map(([slug, videoId, title, duration, tier, clips]) => ({
  id:`grant-${slug}`, speakerId:'grant-sanderson', speaker:'Grant Sanderson', sourceTitle:title, videoId, videoTitle:title,
  channelName:'3Blue1Brown', thumbnail:`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`, duration,
  description:`${tier}-tier transcript-audited explainer. Clips isolate reusable teaching moves rather than quotable lines.`,
  focus:[`${tier} tier`,'Transcript audited','Teaching moves'], status:'ready',
  segments:clips.map(([start,end,label],i):Segment=>({id:`G3B-${slug.toUpperCase().replace(/-/g,'_')}-${String(i+1).padStart(2,'0')}`,start,end,label,lines:[],createdAt:0})),
}))

// Integrity rule: "ready" means timestamped caption text was checked at every selected boundary.
// Chapter markers, summaries, remembered moments, and inferred time ranges never qualify.

export const THREEBLUE_SPEAKER: CuratedSpeaker = {
  id:'grant-sanderson', name:'Grant Sanderson · 3Blue1Brown',
  description:'Explanation study: how Grant makes difficult ideas feel motivated, visual, and almost inevitable. The unit is the teaching move, not the quote.',
  focus:['Explanation','Intuition','Reframing','Mental models','Conceptual compression','Visual reasoning'],
  portrait:'https://i.ytimg.com/vi/WUvTyaaNkzM/hqdefault.jpg', sources,
}
export const THREEBLUE_COLLECTIONS = sources
export const getThreeBlueSpeaker = (id:string|null|undefined) => id===THREEBLUE_SPEAKER.id ? THREEBLUE_SPEAKER : null
export const getThreeBlueCollection = (id:string|null|undefined) => id ? THREEBLUE_COLLECTIONS.find(x=>x.id===id)||null : null
